Webebeb-Workers/algo-workers

Softeer/20250204_징검다리/dbjoung.js
- 문제 이슈 넘버: #7 
- 시간 제한 : JS 2초, c++ 1초
- 메모리 제한 : 256mb
- 철수는 강 위에 놓인 징검다리를 밟으며 서쪽에서 동쪽으로 이동하는데, 다음에 밟을 돌은 지금 밟은 돌보다 높아야 한다.
- 철수가 밟을 수 있는 돌의 최대 개수를 구하라는 말은, 징검다리 5개 중 1번째, 2번째, 3번째를 밟을 수도 있고, 1번째, 3번째, 5번째를 밟을 수도 있고, 4번째, 5번째만 밟을 수도 있고, 딱 하나의 돌만 밟게 될 수 도 있지만 하여튼 그런 경우의 수들 중 가장 돌을 많이 밟은 경우의 누적 돌 수를 구하라는 뜻이다.
- 하지만 N의 최대값이 1000이기 때문에 모든 경우의 수를 계산하면 절대 2초 내로 못 끝낸다. 
- 빡구현 O(n) 추산 = 1000C1000 + 1000C999 + 1000C998 + ... +1000C1
- 따라서 동적계획법을 사용해 각 돌 마다의 '최대 누적 돌 수'를 계산해가며 풀어야 한다.
- 바텀탑 동적계획법을 사용했다.
- d[n]은 철수가 n번째 돌을 밟았을 때의 '최대 누적 돌 수'다.
- 'd[n] = (d[0]부터 d[n-1] 까지의 값 중 최대값)+1' 임을 알 수 있다.
- d 배열 중 가장 큰 값이 정답이다.
- 위 점화식을 그대로 코드로 옮긴다.
- (이후 탑다운으로도 구현해봤지만 시간초과)
- 시간 : O(n) = 1000 * 1000 = 1000000 회 보다 무조건 적음 (0.1초)
- 메모리 : 2000 * 8byte = 16000byte = 0.016mb
- 시간 : O(n) = 0.078초
- 메모리 : 8.01mb
=> [다솔] 250204

Softeer/20250210_점수따먹기/dbjoung.js
- 문제 이슈 넘버: #23 
- 2차원 배열이 입력으로 주어지고, 배열 내 부분행렬 중 값의 합이 가장 큰 행렬의 합을 구해야 한다.
- N, M 최대값 : 30
- 메모리 : 124mb
- 배열 요소값 범위 : -30000~30000
- 인덱스 (1,1) 부터 (n, m) 까지의 부분 행렬의 합을 구하는 것은 dp 활용한 누적합으로 쉽게 해결된다.
- 점화식 : d[a][b] = d[a-1][b] + d[a][b-1] - d[a-1][b-1]
- 하지만 모든 부분 행렬의 합을 비교해야하므로, 2차원 배열로 모든 행렬을 순회하며 d 배열을 활용해 요소 합을 구하도록 한다.
- 부분행렬([a1, b1] 칸부터 [a, b] 칸까지) 요소 합 : d[a][b] - d[a1-1][b] - d[a][b1-1] + d[a1-1][b1-1]
- 4중 for문이 되어버리지만 30x30x30x30 = 810,000 이기 때문에 시간 제한 2초 안에 충분히 풀 수 있을 것이라 생각했다.
- 소요 시간 : 30x30x30x30=810,000 (약 0.0081초) 
- 메모리 : - 
- 소요 시간 : 2552ms (0.2ms)
- 메모리 : 12972 KB
=> [다솔] 250210

Softeer/20250205_징검다리2/rhino-ty.js, Softeer/20250205_출퇴근길/rhino-ty.js
- 문제 이슈 넘버: #16 
동적 계획법의 응용 문제임
- 징검다리는 서쪽에서 동쪽으로 놓여있음, 돌의 높이는 모두 다름
- 철수는 서쪽에서 동쪽으로 이동하면서 처음에는 높이가 점점 높은 돌을 밟고 어느 지점부터는 높이가 점점 낮은 돌을 밟아야 함
- 최대한 많은 돌을 밟으려 할 때, 밟을 수 있는 돌의 최대 개수를 구하는 문제
- 1 ≤ N ≤ 3×10^5 인 정수, 1 ≤ Ai ≤ 10^8 를 2초 안으로 해결
- 즉, 시간초과에 주의해야 함 (O(N²) 사용 불가) => 이걸 몰라서 시간 초과 됐음
1. **문제 분석**
- "산" 모양의 수열을 찾는 문제 -> 바이토닉 수열(Bitonic Sequence)을 뜻함
- 각 돌(`i`)을 기준으로 "왼쪽에서의 증가 수열 길이"와 "오른쪽에서의 감소 수열 길이"를 구해야 함
2. **첫 번째 시도 (O(N^2) - 시간초과)**
- 동적 계획법을 사용한 기본적인 접근
- 각 위치마다 이전/이후의 모든 돌을 검사
- N이 최대 3×10^5이므로 시간초과 발생
3. **최적화된 해결방법 (O(NlogN))**
- 이진 탐색을 활용하여 시간복잡도 개선
- [Lower Bound](https://yoongrammer.tistory.com/105) 개념을 사용해 증가/감소 수열의 위치를 빠르게 찾음
- 시간복잡도: O(NlogN)
- 각 원소마다 이진 탐색: O(logN)
- 전체 원소 순회: O(N)
- 공간복잡도: O(N)
- incLength, decLength 배열: O(N)
- incSequence, decSequence 배열: O(N) …
=> [태연] 250205

Backjoon/250212_개똥벌레/dbjoung.js
- 문제 이슈 넘버: #23 
- 개똥벌레는 무조건 일직선으로 날아간다. 마주치는 종유석과 석순을 전부 부순다. 개똥벌레가 최소로 부수는 개수와, 최소인 트랙이 몇 개 있는 지를 구해야 한다.
- 완전 탐색이나 2차원 DP를 사용해서 풀 수 있겠지만, N과 M의 최대값이 각각 200,000, 500,000 이라서 불가능하다. (총 100000000000회 반복하게 됨.)
- 시간 복잡도가 O(N제곱) 보다 적은 방법을 생각해야 한다. 
- 개똥벌레는 트랙을 무조건 완주하기 때문에, 석순은 석순 끼리, 종유석은 종유석 끼리 자리를 바꿔도 결과가 바뀌지 않는다.
- 각 트랙별 개똥벌레가 부수는 석순과 종유석 수를 각각 계산한 후 합친다. 
- 석순과 종유석의 크기가 오름차순으로 정렬되어있다면, 이분탐색을 활용해 트랙별 부수는 개수를 빠르게 계산할 수 있다.
- 예를 들어 3번 트랙에서 개똥벌레가 달릴 경우, 개똥벌레는 길이가 3 이상인 석순(종유석)만 부술 수 있다. 따라서 전체 석순(종유석)의 개수에서 길이가 3 미만인 석순(종유석)이 몇 개 있는지 계산하여 빼주면 된다.
- 즉, track[i] = N/2 - (i보다 크기가 작은 석순(종유석)의 개수)
- for문을 돌려서 'i보다 크기가 작은 석순(종유석)의 개수'를 직접 세어줘도 괜찮지만, 아마 이러면 시간 초과가 발생할 것이다. 따라서 이분탐색을 활용해 석순(종유석)의 크기 배열에서 i가 몇 번째 자리에 위치하는 지 구하면, (그 인덱스 - 1) 이 곧 'i보다 크기가 작은 석순(종유석)의 개수'가 된다.
***MEMO***
- 오름차순 정렬 : …
=> [다솔] 250212

Backjoon/250212_개똥벌레/ssum1ra.py
- 문제 이슈 넘버: #31 
- n개의 장애물을 하나씩 확인하면서 장애물의 높이만큼 배열을 업데이트한다.
- 최악의 경우, 장애물의 높이가 h에 가까우면 O(h)번 실행된다.
- 전체 n개의 장애물에 대해 실행되므로 총 O(n * h) 연산이 필요하다.
- 시간 복잡도가 O(n * h)
- 최악의 경우(n = 200,000, h = 500,000)에 맞춰 보면 10¹¹번(1000억 번) 이상의 연산이 발생할 수 있어 1초 안에 해결할 수 없다.
> [!IMPORTANT]
> h = 5,
> - **1구역에서 파괴해야 하는 장애물 개수**  
>   - 바닥의 높이 `1, 2, 3, 4, 5`의 방해물 개수 + 천장의 높이 `5` 방해물 개수  
> - **2구역에서 파괴해야 하는 장애물 개수**  
>   - 바닥의 높이 `2, 3, 4, 5`의 방해물 개수 + 천장의 높이 `4, 5` 방해물 개수  
> .
> .
> .
> - **5구역에서 파괴해야 하는 장애물 개수**  
>   - 바닥의 높이 `5`의 방해물 개수 + 천장의 높이 `1, 2, 3, 4, 5` 방해물 개수  
- 입력 시, 종유석과 석순을 각각 다른 배열에 저장한다.
- 종유석(천장) → t[]
- 석순(바닥) → d[]
- 종유석과 석순의 높이별 개수를 기록한다.
- `t_h[i]` : 높이가 i인 종유석의 개수
- `d_h[i]` : 높이가 i인 석순의 개수
- 역방향 누적합 계산을 통해 충돌 개수를 누적한다.
- `dp_d[i] = dp_d[i+1] + d_h[i]` : 바닥의 높이 `i, i + 1, ..., h` 방해물의 …
=> [미라] 250212

Backjoon/250212_개똥벌레/choiseona.js, Backjoon/250216_게임_개발/choiseona.js
- 문제 이슈 넘버: #36 
- 건물 짓는 것에는 순서가 있음
- 건물을 동시에 지을 수 있음 
- 건물 짓는 시간의 최대값을 계속 갱신해나가는 방식으로 하면, 결국엔 선행해서 지어야하는 건물을 모두 지은 후의 시각이 최대값이 될 것이라고 생각해서 단순히 BFS로 풀었음.  
- 방문했던 노드를 또 큐에 push 하게되므로 굉장히 비효율적 -> 시간 초과 
```
Math.max(result[nextNode], result[currentNode] + graph[nextNode].time)
```
- 위의 방법에서 노드를 방문할 때마다 진입 간선을 하나씩 감소 시키는 코드만 추가함
- 진입 간선이 0이 되면 그때 queue에 push하는 방식임
=> [선아] 250216

Backjoon/250217_N-Queen/dbjoung.js
- 문제 이슈 넘버: #41 
- NxN 보드판에 퀸 N개를 서로 잡을 수 없는 위치를 놓는 경우의 수 구하기
- dfs로 완전탐색하며 조건에 맞는 가지수를 구한다.
- dfs 함수가 중첩될 때 마다 row인덱스를 한칸 전진한다.
- dfs 함수 내에서는 col 인덱스를 for 문 돌리며 순회한다.
- 퀸을 놓을 수 있는 칸이라면, 퀸을 놓고 다음 row로 넘어간다.
- 퀸을 놓을 수 있는 조건
- 현재 칸의 가로 줄에 아무것도 놓여있지 않음 (row 값이 같음)
- 현재 칸의 세로 줄에 아무것도 놓여있지 않음 (col 값이 같음)
- 현재 칸과 대각선인 줄에 아무것도 놓여있지 않음 (row+col 값이 같음)
- 현재 칸과 역대각선인 줄에 아무것도 놓여있지 않음 (row-col 값이 같음)
- 위 조건에 해당하는 배열을 각각 생성해 방문 배열로 사용하였음.
- N개의 줄에서 각 줄 당 칸 하나씩 고르므로, 시간 복잡도는 N<sup>N</sup>. 
- 15<sup>15</sup>이 최대값이므로, 적어도 100억회 연산... 시간복잡도 어떻게 통과했지?
- 생각해보니 퀸 놓는 조건에 해당하지 않는 경우의 수는 전부 탐색하지 않고 IF문으로 걸러짐.
- 10992 KB / 4040ms
=> [다솔] 250217

Programmers/250220_가장_많이_받은_선물/dbjoung.js, Programmers/250223_도넛과_막대_그래프/dbjoung.js
- 문제 이슈 넘버: #57 
- 각 캐릭터별 총 받은 선물 수, 준 선물 수를 통해 선물 Point를 구한다.
- 2차원 배열에 누가 누구에게 선물을 줬는 지 기록한다.
- 2차원 배열을 2중 for문으로 순회하면서 <sub>총 사람 수</sub>C<sub>2</sub> 쌍으로 조회한다.
- 둘 중 누가 선물을 받을 사람인지 판별 후, 사람 별 총 받은 선물 수를 기록한다.
- 가장 선물 많이 받은 사람 수를 출력한다.
---
- 문제 이슈 넘버: #58 
- 일자형, 팔자형, 도넛형 그래프가 그려진 상태에서, 노드 하나가 추가된 후 각 그래프의 랜덤한 노드 하나와 간선으로 이어진다.
- 추가한 노드의 번호, 그리고 각 그래프 종류별 개수를 구해야 한다.
1-1. 방문 배열을 만든다. (전부 true로 초기화)
- bfs에 사용할 방문배열. 
1-2. 인접리스트를 만든다. (순방향 1개, 역방향 1개)
- 순방향으로 out 간선을, 역방향으로 in 간선 체크
- 노드 번호가 순차적으로 지정되지 않기 때문에, 실제 존재하는 노드를 visit 배열에 false로 설정한다.
2. 추가 노드를 찾는다.
- out 간선은 2개 이상이고, in 간선은 0개인 노드
3. 추가 노드의 간선들 삭제 
4. 8자형의 중심 노드s 찾음 : out 간선 2개, in 간선 2개
- 해당 배열의 길이가 8자형 그래프의 개수다.
5. 1자형의 시작 노드s 찾음 : out 간선 1개 or 0개, in 간선 0개
- 해당 배열의 길이가 일자형 그래프의 개수다.
6. 8자형 중심 노드, 1자형 중심 노드에서 bfs로 순회하며 vist …
=> [다솔] 250220

Programmers/250303_산_모양_타일링/ssum1ra.py
- 문제 이슈 넘버: #64 
- 1번 타일 : 위쪽 마름모 (a + c)
- 2번 타일 : 왼쪽 마름모 (b + c)
- 3번 타일 : 오른쪽 마름모 (c + d)
- 4번 타일 :  정삼각형 타일 
- k-1번째의 3번 타일과 k번째의 1, 2, 4번 타일은 함께 놓일 수 없다. 
- dp 활용
- array_3 : k번째에 3번 타일을 배치한 경우의 수
- array_124 : k번째에 1,2,4번 타일을 배치한 경우의 수
- array_3[k] = array_3[k-1] + array_124[k-1]
- array_124[k] = array_3[k-1] * 2 + array_124[k-1] * 3
- `array_3[k-1] * 2` (왼쪽 그림) : k-1번째에 3번 타일을 배치한 경우, k번째에 1, 4번 타일 배치 가능
- `array_124[k-1] * 3` (오른쪽 그림) : k-1번째에 1,2,4번 타일을 배치한 경우, k번째에 1,2,4번 타일 배치 가능
- array_3[k] = array_3[k-1] + array_124[k-1]
- array_124[k] = array_3[k-1] * 1 + array_124[k-1] * 2
- `array_3[k-1] * 1` (왼쪽 그림) : k-1번째에 3번 타일을 배치한 경우, k번째에 4번 타일 배치 가능
- `array_124[k-1] * 2` (오른쪽 그림) : k-1번째에 1,2,4번 타일을 배치한 경우, k번째에 2,4번 타일 배치 가능
- 매 반복마다 나머지 계산을 하지 않는다면 시간초과
=> [미라] 250303

Backjoon/250305_타임머신/ssum1ra.py
- 문제 이슈 넘버: #70 
1. 출발 노드를 설정한다.
2. 최단 거리 테이블을 초기화한다.
3. 다음의 과정을 (노드의 개수 - 1)번 반복한다.
- 전체 간선을 하나씩 확인한다.
- 각 간선을 거쳐 다른 노드로 가는 비용을 계산하여 최단거리 테이블을 갱신한다.
- 이때, 최단 거리 테이블이 갱신된다면 음수 간선 순환이 존재하는 것이다.
- 최단 경로는 최대 (노드의 개수 - 1)개의 간선만 포함한다.
-  (노드의 개수 - 1)번 반복하면, 어떤 노드도 더 이상 최단 경로가 갱신되지 않음을 보장할 수 있다.
- 점진적인 갱신
- 1번째 반복 → 출발점에서 1개의 간선만 사용한 최단 경로를 구한다.
- 2번째 반복 → 최대 2개의 간선을 사용한 최단 경로를 구한다.
- ...
- (노드의 개수 - 1)번째 반복 → 최대 (노드의 개수 - 1)개의 간선을 사용한 최단 경로가 구해진다.
- 음수 사이클 검출 
- 따라서, 만약 (노드의 개수 - 1)번을 초과하여 최단 거리가 계속 갱신된다면, 이는 음수 사이클이 존재함을 의미한다.
- 가중치가 없는 경우
- 매번 방문하지 않은 노드 중에서 최단 거리가 가장 짧은 노드를 선택한다.
- 어떤 경로에서 최단 거리를 이루는 전체 경로가 있다면, 그 경로의 부분 경로도 역시 최단 경로가 되어야 한다.
- 즉, 시작점 → A → B가 최단 경로라면, 시작점 → A도 최단 경로여야 한다.
- 음수 간선이 없다면 최적의 해를 찾을 수 있다.
- 매번 모든 간선을 전부 확인한다.
- 따라서 다익스트라 알고리즘에서의 최적의 해를 항상 포함한다.
- 다익스트라 알고리즘에 …
=> [미라] 250305

Programmers/250309_n+1_카드게임/rhino-ty.js
- 문제 이슈 넘버: #79
이 문제를 처음 접했을 때, 핵심 특징을 분석하여 다음과 같은 의사코드를 작성했습니다.
```
// 각 cards마다 탐색 후 n+1이 있으면 뽑기? => 그리디한 방법은 안될 거 같음. 현재 카드보다 미래 카드와의 조합 가능성이 있기 때문
// DFS로 재귀적으로 전체 탐색 후 항상 최대 라운드 변수를 갱신하는 게 좋을 듯, 어차피 맨 아래 노드까지 내려갈 것이니
```
초기에는 각 카드를 뽑은 후 그리디한 방식으로 결정하는 것은 최적의 결과를 보장할 수 없다고 판단했습니다. 
그 이유는
1. **미래 카드와의 조합 가능성** : 현재 손에 든 카드를 미래에 뽑을 카드와 조합하면 더 많은 라운드를 진행할 가능성
2. **전체 경우의 수 탐색 필요** : 각 라운드마다 카드 선택에 대한 여러 경우의 수가 존재하며, 이들의 조합에 따라 결과가 달라짐
- 현재 카드 내에서 13을 낼 수 있고, 현재 뽑은 카드를 먹거나 안먹어서 미래 카드와의 조합을 생각해야한다.
따라서 DFS(깊이 우선 탐색)를 통해 모든 가능한 경우의 수를 탐색하고, 완전 탐색을 통해 최대 라운드 수를 찾는 접근 방법을 선택했습니다.
DFS 방식으로 문제를 해결하기 위해 다음과 같은 단계적 접근을 구현했습니다.
```
1. 초기 변수 설정: 시작 카드(`n/3`장), 동전(`coin`개), 목표 합(`n+1`), 최대 라운드 변수
2. 각 라운드마다 4가지 선택지 탐색:
- 두 카드 모두 버리기
- 카드1만 가져가고 카드2는 버리기 (동전 1개 사용)
- 카드2만 가져가고 카드1은 버리기 (동전 1개 사용)
- 두 …
```
=> [태연] 250309

Baekjoon/250306_평범한_배낭/rhino-ty.js
- 문제 이슈 넘버: #75
처음에는 다음과 같은 의사코드로 접근했습니다.
```
// 여러 경우의 수에 대한 최댓값 => DP를 사용해 최대 가치를 구하기
// 1. DP 생성 : i 번째 물건을 택했을 때, 나오는 최댓값 j가 나오도록
// 2. DP 채우기
//   - 물건들 배열 순회하며 최대 무게 담기
//   - 최대 무게가 나오면 continue
```
이 접근 방법은 배낭 문제의 기본 아이디어를 담고 있었지만, 구체적인 로직과 상태 전이 방식(점화식)이 명확하지 않았습니다.
배낭 문제의 전통적인 방법인 2차원 DP 배열을 사용해 첫 번째 구현을 진행했습니다.
```javascript
function getMaxThingsInBag(N, K, things) {
const dp = Array(N + 1)
.fill()
.map(() => Array(K + 1).fill(0));
// DP 배열 채우기
for (let i = 1; i <= N; i++) {
const [weight, value] = things[i - 1]; // 0-based 배열을 1-based로 변환
for (let w = 0; w <= K; w++) {
if (weight > w) {
dp[i][w] = dp[i - 1][w];
} else {
dp[i][w] = Math.max(dp[i - 1][w], dp[i - 1][w - weight] + value);
}
}
}
return dp[N][K];
}
```
1. **DP 배열 정의**: `dp[i][w]` = i번째 물건까지 고려했을 때, 무게 w를 담을 수 있는 배낭의 …
=> [태연] 250306

Programmers/250310_봉인된_주문/rhino-ty.js
- 문제 이슈 넘버: #83 
- 알파벳 소문자로 구성된 문자열이 다음 규칙에 따라 정렬됨
1. 글자 수가 적은 주문부터 먼저 기록
2. 글자 수가 같다면 사전 순서로 기록
- 특정 문자열들(bans)이 삭제된 후, n번째 문자열을 찾아야 함
1. 직접 n개의 문자열을 생성하는 것은 n이 최대 10^15까지 가능하므로 불가능
2. 특정 숫자를 문자열로 변환하는 방식(26진법 변환)과 금지된 문자열 처리를 조합
처음에는 다음과 같은 의사코드를 계획했습니다.
```
// 1. n번째 문자열의 길이 결정
//   - 각 길이별 문자열 개수 계산하고 범위 체크
//   - 누적합으로 n이 어느 길이 구간에 속하는지 파악
// 2. ban 리스트 처리하기
//   - n번째 문자열보다 사전상 앞에 있는 ban 문자열 개수 세기
//   - 해당 개수만큼 n 값 증가시키기
// 3. 최종 n번째 문자열 생성
//   - n이 속한 길이에서 몇 번째인지 계산
//   - 해당 순서를 알파벳으로 변환
```
- `ban` 목록에서 "n번째 문자열보다 사전상 앞에 있는 것들 개수 세기"가 복잡함
- 각 ban에 대해 정확한 순서 계산이 필요한데, 이를 위한 추가 로직이 복잡해짐
- 직관적으로 코드를 구현하기 어려움
- n번째 문자열을 직접 계산하고, 각 ban과 비교하는 방식으로 단순화
- 더 직관적이고 구현이 간결해짐
1. `orderToSpell` 함수를 통해 숫자를 26진법 문자열로 변환
2. 금지된 문자열(bans)을 길이순, 사전순으로 정렬
3. 각 금지된 문자열을 순회하며:
- 현재 n값에 해당하는 문자열 계산 …
=> [태연] 250310

Programmers/250311_완전범죄/ssum1ra.py
- 문제 이슈 넘버: #87 
- dp[info 인덱스][a의 흔적 개수][b의 흔적 개수]
2시간...
=> [미라] 250311

Programmers/250312_지게차와_크레인/dbjoung.js
- 문제 이슈 넘버: #102 
- 35분 + (+30분?)
- 포크레인으로 꺼낼 경우는 조건 상관 없이 무조건 꺼낼 수 있음.
- 지게차로 꺼낼 경우는 꺼내려는 시점에서 지게차가 접근 가능해야 함
- 포크레인으로 꺼낼 경우는, storage를 순회하며 물건을 찾아 바로 꺼내면 된다.
- 지게차의 경우는 해당 물건이 storage 외부와 연결되어있는 지 확인 후, 연결되어 있으면 꺼내야 한다.
- bfs를 사용해 꺼내려는 물건이 storage 바깥과 통로로 이어져있는 지 확인한다.
- storage에서 이미 꺼낸 물건은 null로 채우고, bfs를 통해 현재 꺼낸 물건의 상하좌우 물건이 null 인지 검사한다. 
- null일 경우 queue에 넣어 그 다음 상하좌우를 같은 방식으로 탐색한다.
- 탐색의 끝에 탐색 인덱스가 storage 범위를 벗어난다면, 바깥과 연결되어있으므로 **꺼낼 수 있는 물건**으로 판단한다.
- **꺼내려는 시점에서 지게차가 접근 가능** 해야 하므로 물건을 찾았다고 해서 바로 꺼내면 안된다. 'AAA' 처럼 같은 물건이 맞붙어 있는 경우를 처리할 수가 없다. 
- 첫 번째 A가 조건을 만족해 null 처리 될 경우, 같은 반복 내 다음 인덱스에서 두 번째 A도 출고 처리되어버린다. 이는 문제의 요구사항과 일치하지 않는다.
- 물건 출고 작업(null 처리)은 현재 출고 건의 반복이 모두 끝난 후 처리해야 한다.
- 50 * 50 * 100 * (bfs 비용. 하지만 그리 크지 않을 것으로 예상)
- 구체적으로 생각해보려 했는데 잘 모르겠음
=> [다솔] 250312

Programmers/250311_완전범죄/dbjoung.js
- 문제 이슈 넘버: #87 
- d[i][B의 누적 흔적 수] = A의 누적 흔적 수
- 1번째 물건을 훔쳤을 때, 2번째 물건을 훔쳤을 때, 3번째... .., ~, i번째 물건을 훔쳤을 때 까지 순회하면서 b의 누적 흔적 수에 따른 a의 누적 흔적 수를 기록한다.
- d[i-1][b] 의 다음 단계는 아래 두 가지 경우로 나뉜다.
- i번째 물건을 A가 훔치는 경우 : d[i][b] = d[i-1][b]+info[i][0]
- A가 훔쳤으므로 점화식의 해만 업데이트.
- i번째 물건을 B가 훔치는 경우 : d[i][b+info[i][1]] = d[i-1][b]
- B가 훔쳤으므로 두 번째 인덱스만 업데이트
- 단, A는 n 이상의, B는 m 이상의 흔적을 남기면 안되므로, 해당 조건을 만족시킬 경우에만 d[i][x]를 업데이트해준다.
- B가 훔치는 경우는 두 번째 인덱스를 업데이트하므로, 이후 b 배열을 순회할 때 중복 업데이트가 될 수 있다. 따라서 Math.min 메소드로 가장 최소값을 유지하도록 한다.
=> [다솔] 250311

Programmers/250313_퍼즐_게임_챌린지/rhino-ty.js
- 문제 이슈 넘버: #108
처음 이 문제를 접했을 때, 여러 접근법을 검토했습니다.
1. **DP(동적 계획법)**: 각 레벨마다 걸리는 시간을 1차원 DP로 선언하는 방법을 고려했으나, `level`에 따른 명확한 점화식을 도출하기 어려움
2. **단순 구현 & 그리디 알고리즘**: 30만 개까지의 입력을 고려하면 모든 가능한 숙련도를 확인하는 것은 비효율적
3. **이진 탐색**: 최종적으로 "매개변수 탐색(Parametric Search)"이라 불리는 이진 탐색 기법 활용 결정
이진 탐색의 활용인 매개변수 탐색(Parametric Search) 방법은 '**제한 시간 안에 퍼즐을 모두 풀 수 있는 가장 낮은 숙련도**'를 효율적으로 찾을 수 있습니다.
1. 숙련도(level)와 소요 시간 사이에는 **단조 관계**가 있습니다 - 숙련도가 높을수록 소요 시간은 적어짐
2. 특정 숙련도로 제한 시간 내에 모든 퍼즐을 풀 수 있는지 확인하는 함수 구현
3. 이진 탐색을 통해 가능/불가능의 경계가 되는 최소 숙련도 결정
이진 탐색에서 중간값을 기준으로 범위를 좁혀나갈 때, 이미 검사한 중간값을 제외하기 위해 `right = mid - 1`과 `left = mid + 1`을 사용합니다. 이러한 +1/-1 처리를 하지 않으면 이미 확인한 값을 다시 검사하게 돼 무한 루프에 빠질 위험이 있습니다.
예시로 순회 도중, `left=1, right=2`일 때 `mid=1`이고, `canResolve(1)`이 `false`를 반환한다고 가정해보겠습니다.
- 올바른 처리: `left = mid + 1`로 설정하여 …
=> [태연] 250313

Programmers/250314_충돌위험_찾기/rhino-ty.js
이 문제는 시뮬레이션 문제로, 여러 로봇이 각자의 경로를 따라 이동할 때 발생하는 충돌 위험 상황을 카운트해야 합니다. 처음에는 직관적인 접근법으로 시작했으나, 대규모 테스트 케이스에서 시간 초과가 발생했습니다.
처음 작성한 코드는 아래와 같은 단계로 동작했습니다.
1. 각 로봇의 전체 경로와 시간별 위치를 모두 먼저 계산해 `robotPositions` 배열에 저장
2. 각 시간대마다 모든 로봇의 위치 배열을 순회하면서 검색(`find`)해 현재 시간의 위치를 찾고, 충돌 카운트
이 접근법의 시간 복잡도는 아래와 같다고 생각했습니다.
- 경로 계산: O(R × P × D)
- R: 로봇 수
- P: 포인트 수
- D: 포인트 간 거리
- 충돌 체크: O(T × R × L)
- T: 총 시간
- C: 각 시간대에 로봇이 존재하는 좌표 수 (R보단 적거나 같음)
테스트 결과, 14-20번 테스트에서 시간 초과가 발생했는데, 이는 `find` 메서드를 사용한 위치 검색 과정(O(L) 시간 소요)이 반복되면서 발생한 성능 병목 현상이 발생했습니다. 
그래서, `find` 메서드 제거하는 방법을 고안해냈습니다.
1. **중간 저장 단계 제거**: 로봇 위치를 모두 계산 후 충돌을 검사하는 대신, 위치 계산과 동시에 맵에 직접 기록
- 기존: 위치 계산 → 저장 → 검색 → 카운트
- 최적화: 위치 계산 → 맵에 직접 기록 → 카운트
2. **자료구조 변경**: 단순 배열 대신 해시 기반 자료구조 사용
- `Map`과 `Set`을 활용해 O(1) 시간에 검색 가능하도록 개선
- 기존: 시간별 검색에 O(L) 소요
- …
=> [태연] 250314

Programmers/250321_수식_복원하기/rhino-ty.js
- 문제 이슈 넘버: #130 
이 문제는 덧셈/뺄셈 수식들을 분석해 고대 문명의 진법을 파악하고, 지워진 결과값들을 채워 넣는 작업입니다. 
초기에는 수식을 파싱하고 진법을 찾는 기본적인 접근법을 구상했습니다. `parseInt('51', 8) - parseInt('5', 8)`와 같은 방식으로 다양한 진법에서 숫자를 변환하고 계산할 수 있다는 통찰에서 시작했습니다.
첫 구현에서는 X가 없는 수식들을 통해 가능한 진법을 필터링하고, 이를 기반으로 X가 있는 수식들의 결과값을 계산했습니다. 그러나 테스트 케이스 4와 5에서 모든 결과가 `?`로 나오는 문제가 발생했습니다.
핵심 문제점들을 발견했습니다.
- **숫자 유효성 검사 부재**: 각 진법에서 사용 가능한 숫자를 사전에 필터링 X
- **진법 추론 로직 불충분**: 예를 들어, 숫자 '7'이 등장한다면 최소 8진법 이상이어야 한다는 중요한 제약을 고려하지 않음
개선된a 해결책은 두 가지 핵심 단계로 구성됐습니다.
1. **사전 진법 필터링**: 모든 수식에서 가장 큰 숫자(digit)를 찾아 이보다 큰 진법만 고려하도록 제한. 예를 들어 숫자 '7'이 있다면 최소 8진법 이상만 고려.
2. **결과값 매핑을 위한 Map 사용**: 각 결과값이 어떤 진법들에서 나오는지 Map을 통해 효율적으로 추적. 이를 통해 모든 진법에서 결과가 동일한지 또는 다른지 쉽게 판별 가능.
`Map`을 사용해 결과값과 진법 간의 관계를 관리해줬습니다.
- 결과값을 키로, 해당 결과가 나온 진법 목록을 값으로 저장
- `resultsByBase.size === 1`로 모든 …
=> [태연] 250321

Programmers/250326_미로_탈출_명령어/ssum1ra.py
- 문제 이슈 넘버: #143 
- dfs 활용
- 그리디하게 탐색 (사전 순으로 먼저 이동)
- 조건
- 현재 위치에서 남은 거리가 맨허튼 거리보다 짧다면, 가지치기
- 현재 위치에서 남은 거리를 맨허튼 거리로 뺀 수가 홀수라면, 가지치기
- ![image](https://github.com/user-attachments/assets/e5eb2ac1-783f-4f25-8f0d-63bac15829e5)
- k = 4일 때, 맨허튼 거리는 3이다.
- k가 홀수일 경우와 짝수일 경우를 생각해보자.
- 남은 거리가 0이고 도착 지점에 도달했다면, 정답
- 1시간 20분 ~ 30분 쯤?
=> [미라] 250326

Programmers/250401_교점에_별_만들기/choiseona.js
- 문제 이슈 넘버: #159 
35분 
1. **모든 직선 쌍의 교점 찾기**
- 두 직선의 방정식 Ax + By + E = 0, Cx + Dy + F = 0의 교점 계산
- 공식 활용: x = (BF - ED) / (AD - BC), y = (EC - AF) / (AD - BC)
- 평행 또는 일치하는 직선 쌍은 제외(AD - BC = 0인 경우)
- 정수 좌표만 포함(나눗셈 결과가 정수인 경우만)
2. **모든 교점의 최소 경계 사각형 찾기**
- 모든 교점 중 x, y 좌표의 최솟값과 최댓값 계산
- 이를 통해 모든 별을 포함하는 최소 크기의 사각형 범위 결정
3. **좌표계 변환 및 별 표시**
- 수학적 좌표계와 배열 인덱스의 방향 차이 해결
- y축: 수학 좌표계(아래→위 증가)와 배열(위→아래 증가)이 반대방향
- x축: 배열은 0부터 시작하므로 최소값(xMin)을 0으로 정규화
- 각 교점 위치에 별표(*) 표시, 나머지는 마침표(.) 표시
=> [선아] 250401

Programmers/250404_광고_삽입/dbjoung.js
- 문제 이슈 넘버: #168 
- 의미 없음
- 단순하게 풀면 시간복잡도 초과.
- 누적합으로 풀어야 한다.
0. 배열에 저장하기 쉽게 시분초를 only 초로 변환한다. 
1. log를 순회하며 startTime 인덱스에는 +1을, endTime 인덱스에는 -1을 한다.
2. 그리고 d[i]+=d[i-1] 점화식으로 누적합을 구하면, 해당 타임에 총 몇 개 구간이 겹쳐있는 지 계산 가능하다.
3. 이후 투포인터 사용해서 광고 시간 구간 중 가장 합이 큰 구간을 찾는다.
4. 주의할 점. endTime은 구간에 포함되지 않음....
- X
=> [다솔] 250404

Programmers/250326_미로_탈출_명령어/rhino-ty.js
- 문제 이슈 넘버: #143
이 문제는 n x m 격자 미로에서 (x, y)에서 출발해 (r, c)로 정확히 k번 이동하여 탈출하는 문제입니다. 같은 격자를 여러 번 방문할 수 있고, 사전순으로 가장 빠른 경로를 찾아야 합니다.
- 격자 바깥으로 나갈 수 없음
- 총 이동 거리가 정확히 k여야 함
- 같은 격자를 여러 번 방문 가능
- 사전순으로 가장 빠른 경로 찾기 (d, l, r, u)
처음에는 최단 경로를 찾는 BFS가 적합하다고 생각했지만, 정확히 k번 이동해야 하고 사전순으로 가장 빠른 경로를 찾아야 하므로 DFS를 사용하기로 결정했습니다.
코드를 작성하기 전에 논리적으로 불가능한 경우를 먼저 필터링하여 효율성을 높였습니다:
- 최단 거리가 k보다 크면 절대 도달할 수 없으므로 "impossible"
- (k - 최단 거리)가 홀수면 도달 불가능 (왕복은 항상 짝수 단위로만 가능)
사전순으로 가장 빠른 경로를 찾기 위해 DFS 탐색 순서를 'dlru' 순으로 설정했습니다. 이렇게 하면 처음 찾은 유효한 경로가 자동으로 사전순으로 가장 빠른 경로가 됩니다.
다음과 같은 가지치기를 통해 불필요한 탐색을 줄였습니다.
- 결과를 이미 찾은 경우 더 이상 탐색하지 않음
- 현재 위치에서 목적지까지의 거리와 남은 이동 횟수를 비교하여 불가능한 경우 탐색 중단
- (남은 이동 - 목적지까지 거리)가 홀수인 경우 불가능하므로 탐색 중단
맨해튼 거리를 사용하여 두 점 사이의 최단 거리를 계산하는 함수를 만들었습니다.
사전순으로 빠른 `'dlru'` 순서로 방향을 정의했습니다. 처음에는 2차원 배열에 튜플로 …
=> [태연] 250326

Programmers/250401_교점에_별_만들기/rhino-ty.js
- 문제 이슈 넘버: #159 
- 여러 개의 직선 ($Ax + By + C = 0$) 형태가 주어졌을 때, 각 직선 쌍의 교점 중 정수 좌표에 있는 점들을 별로 표시해야 함
- 별이 그려진 최소 사각형을 출력해야 함
1. **모든 직선 쌍에 대해 교점 구하기**: 모든 직선 조합을 구해 각 조합마다 교점을 계산
2. **정수 좌표 필터링**: 교점 중 x, y 좌표가 모두 정수인 점만 선택
3. **최소 사각형 찾기**: 모든 정수 교점을 포함하는 최소 크기의 사각형 테두리 계산
4. **별 그리기**: 최소 사각형 안에 정수 교점 위치에 별 표시
1. **직선 간 교점 계산**
- 두 직선의 교점 공식 활용
```
x = (B₁C₂ - B₂C₁) / (A₁B₂ - A₂B₁)
y = (A₂C₁ - A₁C₂) / (A₁B₂ - A₂B₁)
```
- 분모가 0인 경우(평행 또는 일치) 건너뜀
2. **정수 좌표 검사**
- `Number.isInteger()`를 사용해 x, y 좌표가 모두 정수인지 검사
3. **성능 최적화**
- 별도의 조합 배열을 만들지 않고 이중 반복문으로 직접 모든 쌍 처리
- 중복 교점 방지를 위해 `Set` 자료구조 활용
4. **좌표계 변환**
- 수학적 좌표계와 배열 인덱스 사이의 차이를 고려하여 y축 뒤집기
- `row = maxY - y`를 통해 좌표계 변환
- 시간 복잡도
- 직선 개수를 n이라고 할 때, 모든 직선 쌍을 검사하므로 O(n²)
- 별을 그리는 과정은 O(k)로, k는 정수 교점의 수
- 공간 복잡도
- 교점을 저장하는 Set, 결과 배열 등을 고려하면 …
=> [태연] 250401

Baekjoon/250407_DNA_비밀번호/rhino-ty.js
- 문제 이슈 넘버: #173 
이 문제는 DNA 문자열에서 특정 길이(P)의 부분 문자열을 찾되, 그 안에 'A', 'C', 'G', 'T' 각각이 주어진 최소 개수 이상 포함되어야 비밀번호로 사용할 수 있다는 조건이 있습니다.
1. DNA 문자열에서 길이가 P인 모든 부분 문자열을 검사
2. 각 부분 문자열에서 'A', 'C', 'G', 'T'의 개수가 주어진 최소 개수 이상인지 확인
3. 조건을 만족하는 부분 문자열의 개수 세기
처음엔 완전탐색으로 `0~P`, `1~P-1` ... 이런식으로 하려고 했지만 DNA 문자열의 길이가 최대 1,000,000이면서 P만큼의 순회도 또 필요하기 때문에 효율적인 알고리즘이 필요하게 됐습니다.
1. **브루트 포스(완전 탐색)**: 모든 가능한 부분 문자열을 추출하고 검사
- 시간 복잡도: O(S * P) → 최악의 경우 10억 번 이상의 연산 필요
- 구현은 직관적이지만 큰 입력에서 비효율적
2. **슬라이딩 윈도우**: 윈도우를 한 칸씩 이동하며 들어오고 나가는 문자만 처리
- 시간 복잡도: O(S) → 최대 약 백만 번의 연산으로 해결 가능
- 대용량 입력 처리에 효율적
입력 크기를 고려했을 때 슬라이딩 윈도우 접근법이 더 적합하다고 판단했습니다.
1. 기본 설정 및 데이터 초기화
2. 초기 윈도우 설정: 처음 P개 문자에 대한 'A', 'C', 'G', 'T' 개수를 미리 계산
3. 슬라이딩 윈도우 적용: 윈도우를 한 칸씩 이동하면서 빠지는 문자와 새로 들어오는 문자만 처리
4. 유효성 검사 함수: 각 윈도우에서 'A', 'C', 'G', 'T'의 개수가 …
=> [태연] 250407

Programmers/250417_합승_택시_요금/dbjoung.js
- 문제 이슈 넘버: #200 
- 28분
- 플로이드 워셜 알고리즘 사용
- A와 B의 출발지점은 같고, 각자의 집을 향해 갈 때 총 택시비를 구해야 한다.
- 처음부터 각자 택시타고 가거나, 어느 지점까지 합승했다가 합승종료지점부터 각자 택시를 타는 방법이 있다.
- 따라서 합승 종료 지점을 n, 출발지를 s, A와 B의 목적지를 각각 a, b라고 뒀을 때 최소 비용을 아래처럼계산할 수 있다. (board[s][e] = s부터 e까지 가는 최소 비용)
- board[s][n]+board[n][a]+board[n][b]
- 플로이드-워셜은 각 노드에서 다른 각 노드로 이동하는 최소 비용을 구할 수 있는 알고리즘이므로, 이를 활용해 각 노드에서 다른 각 노드까지의 최소 비용을 구한 다음, n의 노드를 하나씩 대입해보며 위 공식의 최솟값을 찾는다.
- 200 * 200 * 200 = 8,000,000
=> [다솔] 250417

Baekjoon/250415_부분합/rhino-ty.js
- 문제 이슈 넘버: #190 
이 문제는 연속된 수들의 부분합 중 그 합이 S 이상이 되는 것 중 가장 짧은 것의 길이를 구하는 과제였습니다. 처음에는 모든 부분 배열을 탐색하는 O(N²) 방식을 생각했지만, 실행 시간이 0.5초라 투포인터 알고리즘을 활용해 O(N) 시간 복잡도로 최적화하도록 결정했습니다.
- 두 개의 포인터(`start`, `end`)를 활용해 연속된 부분 배열을 효율적으로 탐색
- 시작/끝 포인터가 0부터 시작해, 증가 및 감소 하면서 조건에 맞는 구간을 찾아감
>[!NOTE]
>배열이나 리스트와 같은 선형 자료구조에서 두 개의 포인터를 이용해 원하는 결과를 얻는 알고리즘
이 두 포인터는 같은 방향으로 이동하거나(동일 방향 투포인터), 서로 반대 방향으로 이동하면서(양방향 투포인터) 문제를 해결합니다.
아래와 같은 상황에서 사용하면 좋습니다.
1. **부분 배열/문자열 문제**: 합이 특정 값인 부분 배열, 특정 문자로만 이루어진 가장 긴 부분 문자열
2. 고정 크기가 아닌 **가변 크기의 윈도우**가 필요한 경우
3. **정렬된 배열에서의 검색**: 두 수의 합이 특정 값과 같은 쌍 찾기, 세 수의 합이 0인 조합 찾기
1. 시작(`start`)과 끝(`end`) 포인터를 모두 배열의 첫 위치(0)에서 시작
4. 현재 부분합(`curSum`)과 최소 길이(`minLength`) 초기화
5. `end` 포인터를 오른쪽으로 이동하며 부분합을 키움
6. 부분합이 `S` 이상이 되면
- 현재 길이(`end-start+1`)와 저장된 최소 길이를 비교하여 더 작은 값을 유지
- `start` …
=> [태연] 250414

Baekjoon/250416_하늘에서_별똥별이_빗발친다/rhino-ty.js
- 문제 이슈 넘버: #197 
이 문제는 N×M 크기의 구역에 떨어지는 K개의 별똥별을 L×L 크기의 트램펄린으로 최대한 많이 튕겨내야 하는 상황입니다. 처음에는 완전 탐색으로 모든 위치(0부터 N-L, M-L까지)에 트램펄린을 놓아보는 방법을 생각했지만, 이렇게 하면 시간 복잡도가 O(N×M×K^2)가 되어 N, M이 최대 500,000이고, K는 최대 100^2 이므로 시간 초과가 날 가능성이 높았습니다.
문제 해결의 핵심 통찰은 **트램펄린의 최적 위치가 별똥별의 좌표와 직접적인 관련이 있다**는 것입니다. 특히, L×L 크기의 트램펄린을 배치할 때 가장 많은 별똥별을 포함하기 위해서는 트램펄린의 모서리나 경계선이 별똥별의 위치와 일치하는 경우가 최적해가 됩니다.
즉, 만약 트램펄린 내부에만 별똥별이 있고 경계에는 없다면, 트램펄린을 약간 움직여서 더 많은 별똥별을 포함할 가능성 존재 하기 때문에,
따라서 최적의 배치는 트램펄린의 경계에 별똥별이 위치한 경우입니다.
1. 모든 별똥별 쌍 (i, j)에 대해
- 별똥별 i의 x좌표와 별똥별 j의 y좌표를 사용해 트램펄린의 좌측 상단 모서리 위치 결정
- 이 위치에 L×L 크기의 트램펄린을 배치했을 때 포함되는 별똥별 수 계산
2. 이를 통해 최대로 튕겨낼 수 있는 별똥별 수를 찾고, 전체 별똥별 수에서 빼서 지구에 부딪히는 별똥별의 최소 수 산출
이 방법은 N×M 전체를 순회하는 대신, K개의 별똥별 쌍만 고려하므로 시간 복잡도가 O(K²×K) = O(K³)가 됩니다. K는 최대 100이므로 1,000,000번 정도의 연산으로 해결 가능하여 …
=> [태연] 250416

Baekjoon/250509_게리맨더링/rhino-ty.js
- 문제 이슈 넘버: #248 
선거구를 두 개로 나눠 인구 차이를 최소화하는 문제였습니다. 핵심 조건은 각 선거구가 연결돼 있어야 한다는 점이었습니다.
처음 문제를 읽었을 때, 구역을 두 개의 선거구로 나누는 모든 경우의 수를 확인해야 한다는 점에서 완전 탐색이 필요하다고 판단했습니다. N이 최대 10이라는 작은 규모였기 때문에, 최악의 경우 $O(2^N)$의 시간복잡도도 감당할 수 있다고 생각했습니다.
그리고, 완전 탐색을 하기 전에, 전체 그래프의 구조를 먼저 파악하면 불필요한 계산을 줄일 수 있을 것이라고 생각했습니다. 그래서 연결된 컴포넌트를 먼저 분석하는 전략을 세웠습니다. 
전체 그래프의 연결된 노드 뭉치, 즉 컴포넌트를 먼저 분석하는 전략을 세웠습니다.
1. 컴포넌트가 3개 이상이면 → 2개의 연결된 선거구를 만들 수 없으므로 -1 반환
2. 컴포넌트가 2개면 → 각각이 하나의 선거구
3. 컴포넌트가 1개면 → 조합을 통해 가능한 모든 경우 탐색
이 접근법으로 불필요한 계산을 줄이고 효율적으로 문제를 해결할 수 있다고 판단했습니다.
1. **그래프 생성**: 인접 리스트 방식으로 구역 간 연결 관계 표현
2. **컴포넌트 분석**: BFS를 활용한 전체 그래프의 연결 컴포넌트 개수 확인
3. **케이스별 처리**
- 컴포넌트 3개 이상: 즉시 -1 반환
- 컴포넌트 2개: 각 컴포넌트의 인구 합산 후 차이 계산
- 컴포넌트 1개: 비트마스크로 모든 조합 생성 → 각 조합의 연결성 확인 → 인구 차이 최소값 탐색
연결 컴포넌트를 먼저 분석함으로써
- 불가능한 경우를 빠르게 판별
- 단순한 …
=> [태연] 250509

Baekjoon/250421_비슷한_단어/rhino-ty.js
- 문제 이슈 넘버: #210
- N개의 영단어들 중에서 **가장 비슷한 두 단어**를 찾는 문제
- 두 단어의 비슷한 정도는 **공통 접두사의 길이**로 측정함
- 접두사란 두 단어의 앞부분에서 공통적으로 나타나는 부분문자열
- 접두사 길이가 최대인 경우가 여러 개일 때는 입력 순서대로 앞쪽에 있는 단어 쌍을 선택
처음에는 이 문제를 어떻게 최적화할 수 있을지 고민했습니다. 가능한 접근법들을 고려해봤습니다.
1. **브루트 포스 방식**: 모든 단어 쌍을 비교하여 공통 접두사 길이를 계산하는 방법 - $O(N²×L)$
2. **최적화된 브루트 포스**: 각 단어 쌍을 한 번만 비교 `(i,j)`와 `(j,i)`는 같으므로 - $O(N(N-1)/2×L)$
3. **정렬 기반 접근법**: 단어들을 정렬하여 인접한 단어들 간의 공통 접두사를 찾는 방법
정렬 기반 접근법도 고려했지만, 문제의 요구사항(입력 순서 유지)과 모든 단어 쌍을 비교해야 하는 필요성 때문에 결국 최적화된 브루트 포스 방식을 선택했습니다.
1. **초기화**: 최대 접두사 길이와 해당 단어 쌍의 인덱스를 추적할 변수 설정
2. **중복 없는 비교**: 모든 단어 쌍을 중복 없이 비교하기 위해 이중 반복문 최적화
- `i`는 0부터 N-2까지, `j`는 i+1부터 N-1까지 순회
3. **접두사 길이 계산**: 각 단어 쌍마다 공통 접두사 길이를 계산
4. **최대값 갱신**: 더 긴 접두사를 찾으면 최대값과 해당 단어 쌍 갱신
5. **순서 고려**: 같은 길이의 접두사인 경우, 입력 순서를 고려하여 우선순위 결정
- 최악의 경우: …
=> [태연] 250421

Baekjoon/250428_거짓말/rhino-ty.js
- 문제 이슈 넘버: #227 
이 문제는 지민이가 파티에서 진실 또는 과장된 이야기를 할 때, 거짓말쟁이로 알려지지 않으면서 최대한 많은 파티에서 과장된 이야기를 할 수 있는 수를 구하는 문제입니다.
주의할 점은 **거짓말을 듣고, 진실을 들으면 안됩니다**. 이후 진실을 들어야할 애들도 예측해서 전체 구라를 구해야합니다.
진실을 아는 사람들의 집합이 파티를 통해 확장되는 과정을 시뮬레이션했습니다.
1. **집합(Set) 자료구조** 활용: 진실을 아는 사람들 관리
2. **반복 확산 알고리즘** 적용
- 진실을 아는 사람들의 집합이 더 이상 변하지 않을 때까지 반복
- 각 반복에서 진실을 아는 사람이 참석한 파티의 모든 참가자를 진실을 아는 사람들의 집합에 추가
- **파티의 순서에 상관없이** 진실을 알게 되는 모든 사람들을 파악하는 것이 중요
- 모든 파티에서 **한 명이라도 진실**을 알면 그 파티의 **모든 참가자는 진실**을 들어야 함
- 파티 순서에 따른 의존성을 고려해 반복적으로 진실을 아는 사람들의 집합을 확장해야 함
- O(M * P * K)
- M: 파티의 수
- P: while 루프의 최대 반복 횟수 (최악의 경우 진실을 아는 사람 수와 비슷)
- K: 각 파티의 평균 참가자 수
이 알고리즘은 문제의 제약 조건(N, M ≤ 50)에서 충분히 가능합니다.
=> [태연] 250428

Baekjoon/250520_파일_합치기/ssum1ra.py
- 문제 이슈 넘버: #260 
```py
for l in range(2, K+1):
for i in range(1, K - l + 2):
j = i + l - 1
dp[i][j] = float('inf')
for k in range(i, j):
dp[i][j] = min(dp[i][j], dp[i][k] + dp[k+1][j] + (prefix_sum[j] - prefix_sum[i-1]))
```
- i번부터 j번까지 파일을 하나로 합치려면, 중간에 k를 기준으로 두 덩어리로 나누고, 각각을 최소 비용으로 합친 뒤, 그 둘을 한 번 더 합쳐야 한다.
- 이 마지막 합치는 비용은 전체 구간의 크기이므로 sum(i~j)을 더해주고, 가능한 k들 중 최소를 선택한다.
- 파일 합치기 문제에서는 구간이 커질수록 최적의 분할점 k도 오른쪽으로 이동하는 경향이 있다.
- 최적의 k가 어디 있는지 이미 좁혀져 있으니까 전체 i ~ j를 다 볼 필요 없이 
- opt[i][j - 1] ~ opt[i + 1][j] 사이에서만 보면 돼서 시간 복잡도가 O(N³) → O(N²)로 줄어든다.
- 1시간 + α
=> [미라] 250520

Baekjoon/250604_숨바꼭질_4/choiseona.js, Programmers/250604_의상/choiseona.js, Programmers/250604_전화번호_목록/choiseona.js
- 문제 이슈 넘버: #293 
40분
- 모든 간선의 가중치가 동일하므로, 최단 경로를 구하는 데 BFS가 적절
- BFS로 탐색하면서 방문한 노드를 기록하고, 각 노드에 대해 **어디서 왔는지(parent)**를 저장
- 이미 방문한 위치는 다시 방문하지 않기 위해 `visited` 배열 사용 (`O(1)` 조회 성능).
- BFS 종료 시점에 도착한 노드 `K`에서부터 `parent` 배열을 따라 `N`까지 거꾸로 올라가며 경로를 복원
- 이때 경로는 역순이기 때문에 `reverse()`로 정렬하여 출력
- 문자열을 **사전순으로 정렬**하면, 접두어 관계가 있다면 반드시 **바로 인접한 항목** 사이에 존재
- 예를 들어 `["119", "1195524421", "97674223"]`으로 정렬되면 `119`와 `1195524421`을 비교하면 바로 확인 가능.
- 인접한 두 전화번호 (`i`, `i+1`)를 비교하면서 `phone_book[i+1].indexOf(phone_book[i]) === 0`인 경우,
- `phone_book[i]`가 `phone_book[i+1]`의 접두어라는 의미이므로, false를 반환
- `Map` 을 사용해 각 의상 종류별로 몇 개의 아이템이 있는지 셈 
- 각 종류에서 **해당 의상을 입지 않는 경우(=1)** 도 포함하여 `(의상 개수 + 1)` 을 곱함 
- 예) 얼굴(2개), 상의(1개), 하의(1개), 겉옷(1개)  
→ (2+1) * (1+1) * (1+1) * (1+1) = 3 * 2 * 2 * 2 = 24가지
- 최종 조합 수 = 전체 경우의 수 - 1
=> [선아] 250604
