- Softeer/20250203_나무_섭지/ssum1ra.py
> 단, 유령은 필요에 따라 움직이지 않아도 됨에 유의합니다.
유령이 출구에 먼저 도착해 기다릴 수 있다.
남우가 유령보다 먼저 출구에 도착할 수 있는가 
- 남우의 출구까지의 최단 거리를 구한다
- bfs 활용
- 유령의 출구까지의 최단 거리를 구한다
- 직선 거리 활용
**최종 판단** : 두 최단 거리가 같거나 남우의 최단거리가 더 크다면 실패
- 유령이 없는 경우도 고려해야 한다.
수정 전
```py
ans = 'Yes'
for (gx, gy) in ghosts:  # ghosts가 비어있으면 이 루프는 실행 안됨
ghost_dist = abs(end[0] - gx) + abs(end[1] - gy)
if dist[end[0]][end[1]] >= ghost_dist:
ans = 'No'
break
```
수정 후
```py
if dist[end[0]][end[1]] == float('inf'):
ans = 'No'
else:
for (gx, gy) in ghosts:
ghost_dist = abs(end[0] - gx) + abs(end[1] - gy)
if dist[end[0]][end[1]] >= ghost_dist:
ans = 'No'
break
```
> [미라] 250203

- Softeer/20250203_나무_섭지/kwaksj329.js
나무가 출구까지 가는 거리 < 유령이 출구까지 가는 거리일 때 나무가 더 빨리 탈출해 `YES`를 출력하도록 구현
따라서 먼저 같은 BFS 함수를 사용하도록 했습니다.
모든 유령에 대해서 순회하는 로직을 사용했기 때문에 시간초과가 났습니다.
따라서 같은 BFS 함수를 사용하되, 유령의 경우 출구에서 출발하여 유령을 마주치는 거리로 계산하도록 수정했습니다.
> 마지막에 급하게 출구 > 유령으로 가는 로직으로 수정해 코드가 예쁘지 않습니다. ^^...
> [수정] 250203

- Softeer/20250203_나무_섭지/dbjoung.js
- 시간제한 : JS 2초, C++1초
- 메모리 제한 : 1024mb
- 진우는 장애물(벽, 유령)을 통과 못하지만, 유령은 통과할 수 있다.
- 유령의 움직임에는 1초에 한 칸 이동하는 것 말고는 딱히 규칙성이 없다. 그저 진우를 잡기 위해 최대한 노력한다.
- 결국 유령이 진우보다 출구에 먼저 도착할 수 있으면 탈출 불가능한 것이고, 도착할 수 없으면 탈출 가능한 것이다. (이 외 경우의 수가 있나 따져봤지만 없는 것 같다.)
- 따라서 진우가 탈출 가능하려면 아래 두 가지 조건을 동시에 만족하면 된다.
- 1. 진우 ~ 출구 최단 경로 < (출구와 가장 가까운) 유령 ~ 출구 최단 경로
- 2. 진우 ~ 출구 경로가 장애물(유령, 벽)로 안 막혀있음.
- 진우~출구 최단 경로 구하기 : bfs로 각 칸까지의 최단 경로를 계산한다.
- 유령~출구 최단 경로 구하기 : 유령에겐 장애물이 없으므로 각 x, y 좌표값 차이의 절대값을 더하면 된다.
- 진우~출구 경로가 장애물로 막혔는 지 확인 : bfs 순회가 출구까지 닿지 못하면 막힌 것.
1. map 입력받는다.
2. 남우 중심으로 bfs 돌리며 출구까지의 최단거리 구한다.
if (거리 배열에서의 출구index 값 == null) 탈출 못함
3. 출구와 가장 가까운 유령의 출구까지의 최단거리 구한다.
if (준우와 출구의 최단 거리 < 유령과 출구의 최단 거리) 탈출함
else 탈출 못함
- O(n) = 1000 * 1000 * 4 = 4000000 회 (1억회 = 1초라 쳤을 때 약 0.04초)
- 메모리 : 1000 * 1000 * 8byte = …
> [다솔] 250203

- Softeer/20250203_나무_섭지/choiseona.js
1. 유령 먼저 BFS로 최단거리로 움직인다. 
2. 남우를 BFS로 각 격자를 최단거리로 움직인다. 이때, 남우의 최단거리보다 유령의 최단거리가 더 짧으면 그 경우는 제외한다(queue에 넣지 않는다.)
3. 결과적으로 남우가 도착지에 방문한 적이 없으면 No를, 도착지에 방문한 적이 있으면 Yes를 출력한다.
시간 초과 발생
> [선아] 250203

- Softeer/20250204_징검다리/kwaksj329.js
- 문제 이슈 넘버: #7 
- 처음에는 그리디 알고리즘으로 풀었으나 `최대`라는 조건을 나중에 발견하여 완전탐색/DP로 접근 방법을 변경했습니다.
- 완전 탐색 시 시간초과를 우려해 DP로 문제를 해결했습니다.
- 이전 돌들을 순회하며 나보다 작은 돌이 있을 때 기존 최적의 답 vs 방금 발견한 작은 돌 밟은 후 답을 비교해 저장합니다.
- 이후 DP 배열에 저장된 답들 중 최댓값을 출력하도록 했습니다.
> [수정] 250204

- Softeer/20250204_징검다리/ssum1ra.py
- 문제 이슈 넘버: #7 
이전까지의 개수를 다시 셀 필요가 없다.
- dp를 활용하여 간단하게 풀 수 있는 문제
> [미라]250204

- Softeer/20250204_징검다리/choiseona.js
- 문제 이슈 넘버: #7 
- 이전 돌이 현재 돌보다 작으면 dp[현재돌] = dp[이전돌]+1
- 이전 돌이 현재 돌과 같으면 dp[현재돌] = dp[이전돌]
- 이전 돌이 현재 돌보다 크면
- 이전돌들 중에 현재돌보다 작은거 있으면 dp[현재돌] = dp[이전돌들 중에 현재돌 보다 작은 것] + 1
- 이전돌들 중에 현재돌보다 작은거 없으면 dp[현재돌] = 1
---
dp 최약체 최서나,,, ㅜㅜ
> [선아] 250204 

- Softeer/20250205_징검다리2/ssum1ra.py
- Softeer/20250205_출퇴근길/ssum1ra.py
- 문제 이슈 넘버: #16 
높이가 점점 높아졌다가 다시 점점 낮아지는 돌을 밟을 수 있는 최대 개수를 구하는 문제이다.
- dp 활용
- dp 활용
- 각 돌을 기준으로 앞에서부터 증가하는 최대 개수와 뒤에서부터 증가하는 최대 개수를 합친 후, 그 중 가장 큰 값을 선택한다.
- dp를 구할 때, for문을 사용하여 풀면 O(N^2)의 시간 복잡도가 발생하므로 시간 초과가 발생한다.
- 이분 탐색을 이용하여 O(N log N)으로 해결해야 한다.
---
- 문제 이슈 넘버: #17 
주어진 그래프에서, 출근길(S > T)과 퇴근길(T > S) 경로 모두에 포함될 수 있는 정점의 개수를 구하는 문제이다.
- S에서 출발하여 도착할 수 있는 모든 노드를 알아낸다.
- 단순하게 dfs나 bfs로 알아낼 수 있다.
- 노드가 많을 경우, N에서 T로 가는 모든 경로를 찾는 데 시간이 오래 걸릴 수 있다.
- 그러나, T > N는 위와 같이 단순하게 dfs나 bfs로 알아낼 수 있다.
- 역방향 그래프를 만들어 T로 올 수 있는 모든 노드를 알아낸다.
> T > N > S의 경우도 동일하다.
- S = 6, T = 5
- 순방향 그래프 (S > N) : S > 3 > 1 > 5 > 4
- 역방향 그래프 (T > N) : T > 1 > 4
- S > N > T를 만족하지만, 4는 중간 노드가 될 수 없다.
- 도착지점에서는 더 이상 움직이지 않기 때문에 이런 경우는 제외해야 한다.
- S > N 경로를 찾을 때, T에 도달하면 더 이상 다른 노드로 진행하지 않도록 해야 한다.
- T > N 경로에서는 S를 여러 번 …
> [미라] 250205

- Softeer/20250205_징검다리2/dbjoung.js
- Softeer/20250205_출퇴근길/dbjoung.js
- 문제 이슈 넘버: 
- 풀이 방법
- 징검다리1을 풀었던 방식인 DP로 접근하면 시간제한에 마주칠 수 밖에 없다. 시간복잡도가 n제곱 미만인 풀이법을 고민해야했다.
- 구글 검색을 통해 이진탐색으로 최장길이수열을 구하는 법을 알게 되어, 해당 방법으로 풀어냈다.
- 돌을 밟고 올라갈 때의 밟은 돌 위치 별 최장 길이 수열 배열을 계산하고, 반대 방향에서 돌을 밟고 올라갈 때의 돌 위치 별 최장 길이 수열 배열도 계산했다.
- 이후 두 최장 길이 수열의 인덱스별 합을 구해, 가장 큰 합을 결과로 출력하였다.
- 문제 이슈 넘버: 
- 풀이 방법
- 단순하게 S(출발점)에서 E(도착점) 까지 밟게 되는 노드를 체크하고, E에서 S까지 밟게 되는 돌을 체크하여 중복되는 노드의 수를 계산하였으나 반례도 있었고, 시간 초과도 발생했다.
- 위 두 가지 체크값만 비교하면 S->E 일 때는 밟는데, E->S일 때는 밟지 않는 돌도 카운트되는 반례가 있었다.
- 해당 문제를 해결하기 위해 아래 네 가지 노드를 체크한 후, 중복되는 노드 수를 계산했다.
- S에서 출발하는 루트 (E를 만날 경우 종료)
- S로 들어오는 루트 (역방향 행렬을 사용해 시간 복잡도 단축)
- T에서 출발하는 루트
- T로 들어오는 루트 (역방향 행렬을~ '')
_*시간복잡도 계산은 패스_
> [다솔] 250205

- Softeer/20250210_점수따먹기/choiseona.js
- 문제 이슈 넘버: #23 
- rowStart, rowEnd, columnStart, columnEnd 둬서 각 인덱스를 증가시키면서 그때마다의 부분 행렬의 합 구해서 최대값 갱신
- 인덱스가 바뀔 때마다 매번 다 계산하므로 매우 매우 비효율적임 
O(N^3 * M^3) -> O(N^6) 
-  각 위치에서의 누적합 미리 구하고, 이걸 이용해 특정 구간의 부분합 구하기
```js
sum[i][j] = map[i][j]  + sum[i][j-1] + sum[i-1][j] - sum[i-1][j-1];
```
여기서 sum[i-1][j-1]을 빼주는 이유는 sum[i][j-1]와 sum[i-1][j]를 더할 때 sum[i-1][j-1]이 두 번 더해지기 때문임
```js
partialSum = sum[rowEnd][columnEnd] - (sum[rowStart-1][columnEnd] + sum[rowEnd][columnStart-1]) + sum[rowStart-1][columnStart-1]
```
여기서 sum[rowStart-1][columnStart-1]을 더해주는 이유는 sum[rowStart-1][columnEnd]와 sum[rowEnd][columnStart-1] 을 뺄 떄 두 번 빼졌기 때문임 
O(N^2 * M^2) -> O(N^4)
> [선아] 250210

- Softeer/20250210_점수따먹기/ssum1ra.py
- 문제 이슈 넘버: #23
```
data[i][j]=A[i][j]+data[i−1][j]+data[i][j−1]−data[i−1][j−1]
```
```
-27 = -22 + 16 + (-16) - 5
```
```
부분합=data[i][j]+data[x−1][y−1]−data[i][y−1]−data[x−1][j]
```
```
- 48 = -103 + 2 - (-15) - (-38)
```
- python3에서 시간초과
- 부분 행렬을 행 기준으로 압축하기
- 변환된 배열에서 연속된 부분 합의 최댓값 찾기 (카데인 알고리즘)
- 이전 인덱스가 갖고 있는 최대 부분합을 연장할지, 아니면 자신의 값으로 초기화할지 선택
> [미라] 250210

- Backjoon/250212_개똥벌레/choiseona.js
- 문제 이슈 넘버: #31 
- 장애물의 높이만큼 배열 갱신 
- 동굴 높이가 H, 동굴 길이가 N 이므로 시간복잡도: O(N*H)
- 장애물 높이 별 개수 구한 후 자신보다 높은 장애물 개수 누적값(부딪히는 개수) 구하기
- 시간 복잡도: O(N + H) 
<br/><br/>
**1. 장애물 높이 별 개수 구하기**
**2. 부딪히는 개수: 자신보다 높은 장애물의 개수 누적값**
**3. 종유석 + 석순 총 부딪히는 개수 구하기**
**4. 최소값 구하기**
> [선아] 250212 

- Backjoon/250216_게임_개발/ssum1ra.py
- 문제 이슈 넘버: #36 
- 위상 정렬, dp 활용
- q에 시간 계산이 끝난 노드를 삽입한다.
- q에서 한 노드를 뽑은 다음, 그 노드 이후 올 수 있는 노드들에 대해 다음과 같은 처리를 한다. 
- `현재 노드를 짓는데 걸린 시간 + 다음 노드를 짓는데 걸리는 시간`과 `지금까지 계산해 온 다음 노드를 짓는 시간`을 비교한다.
- 그 중에 큰 값이 다음 노드를 짓는데 걸리는 시간이 된다.
- 예를 들어, 아래와 같은 경우를 보면 빌딩 3이 지어지기 위해선 25초가 걸린다.
- ![image](https://github.com/user-attachments/assets/8fb69a2a-e47c-4f2f-824b-d5635421fb32)
- 더 이상 노드로 들어오는 진입차수가 없는 경우, 노드 짓는 시간 계산을 중지하고 큐에 삽입한다.
> [미라] 250216

- Backjoon/250216_게임_개발/rhino-ty.js
- 문제 이슈 넘버: #36
- **주어진 조건**
- 건물을 짓는데 필요한 선행 건물들이 존재
- 여러 개의 건물을 동시에 지을 수 있음 (병렬 처리 가능)
- 각 건물의 건설 시간과 선행 관계가 주어짐
- **핵심 포인트**
- 선행 조건(의존성) 처리 → 위상 정렬
- 병렬 처리 가능 → MAX 값 활용
- 각 건물별 최종 완성 시간 계산 → DP
```
// 1. 각 건물들마다의 걸리는 시간을 저장할 DP 생성
// 2. 건물들을 순회하며 걸리는 시간 계산 및 저장
//   - 현재 건물에 필요한 선행 건물들의 시간 확인
//   - 선행 건물들 중 가장 오래 걸리는 시간을 찾는다 (MAX값)
//   - 현재 건물의 완성 시간 = MAX값 + 현재 건물의 건설 시간
```
- 건물 번호가 꼭 선행 순서대로 주어지지 않을 수 있음
- 예시: `1번 건물이 2번 건물을 필요로 하는 경우`
- 해결책: 위상 정렬 도입 필요
```
// 1. 각 건물들마다의 걸리는 시간을 저장할 DP 생성
// 2. 입력을 받으며
//    - 2차원 배열에 건물 간의 관계 저장
//    - 각 건물의 진입차수 계산
// 3. 그래프에서 진입차수가 0인 건물들부터 순회하며 걸리는 시간 계산 및 저장
//   - 현재 건물에 필요한 선행 건물들의 시간 확인
//   - 선행 건물들 중 가장 오래 걸리는 시간을 찾는다 (MAX값)
//   - 현재 건물의 완성 시간 = MAX값 + 현재 건물의 건설 시간
```
```javascript
const dp = new Array(N + 1).fill(0);          // …
```
> [태연] 250216

- Backjoon/250217_N-Queen/choiseona.js
- 문제 이슈 넘버: #41 
1. **백트래킹**:
- 각 행에 대해 모든 열 시도
-  `checkIsPossible(row)` 함수로 유효성 검사 후 유효한 위치이면 다음 행으로 이동 (`DFS(row + 1)`)
- 만약 불가능한 위치라면, 다른 열을 시도하고, 모든 열을 시도한 후 되돌아가서 이전 행으로 돌아가 다른 위치를 시도.
- 모든 행에 대해 퀸을 놓을 수 있으면, `answer`를 증가시킴
2. **`checkIsPossible(row)`**: 현재 `row`에 퀸을 배치할 수 있는지 확인
- `queen[prevRow] === queen[row]`: 같은 열에 퀸이 있는지
- `Math.abs(row - prevRow) === Math.abs(queen[row] - queen[prevRow])`: 대각선 상에 퀸이 있는지
> [선아] 250217

- Backjoon/250218_Dance_Dance_Revolution/rhino-ty.js
- 문제 이슈 넘버: #47 
- DDR 게임판의 상태 관리 => 3차원 DP 배열 구현으로 모든 상태 저장
- 각 스텝에서의 최소 힘이 이전 스텝들의 발 위치에 의존
- 현재 왼발 위치
- 현재 오른발 위치
- 현재까지 진행한 스텝
- 양발의 위치/이동에 대한 다양한 경우의 최소 힘의 합을 구하는 거니, DP 문제
- 발의 위치에 따른 힘 사용 규칙이 존재
- 중앙(0)에서 다른 지점 : 2
- 같은 지점 재사용 : 1
- 인접 지점 이동 : 3
- 반대편 이동 : 4
```javascript
// 점화식 :
//   - 0 => 다른지점 : 2
//   - 같은지점 또 누르면 : 1
//   - `| 다른지점 => 다른지점의 차 |`가 1, 3일 때 : 3
//   - `| 다른지점 => 다른지점의 차 |`가 2일 때 : 4
function getPower(start, end) {
if (start === 0) return 2;
if (start === end) return 1;
const minusAbs = Math.abs(start - end);
if (minusAbs === 1 || minusAbs === 3) return 3;
if (minusAbs === 2) return 4;
}
```
왼발 위치 (0 ~ 4), 오른발 위치 (0 ~ 4), 현재 스텝 (N개) 각각이 독립적인 형태임. 또한, 1~2차원으로는 다른 발의 위치 정보를 저장할 수 없음. 그래서 3차원 배열 사용.( + 상수 및 인덱스 순회가 아닌 호출 식으로 많이 사용하다 보니 시간복잡도 괜찮다고 판단)
각각의 스텝들을 0부터 …
> [태연] 250218

- Backjoon/250217_N-Queen/rhino-ty.js
- 문제 이슈 넘버: #41
- N × N 체스판에 N개의 퀸을 배치하는 모든 경우의 수를 찾는 문제
- 퀸은 가로, 세로, 대각선 방향으로 이동 가능
- 완전 탐색으로는 시간 복잡도가 O(2^(N×N))로 너무 높음
- DFS(재귀)와 백트래킹을 조합해 해결 필요
- 2차원 배열로 체스판 구현
- `board[row][col] = true/false`로 퀸의 위치 표시
- 같은 열에 퀸이 있는지 확인
- 대각선 상에 퀸이 있는지 확인
- 절댓값을 활용한 대각선 체크 최적화 : `|현재 행 - 이전 행(i)| === |현재 열 - 놓인 퀸의 열 위치|`
```javascript
Math.abs(row - i) === Math.abs(col - board[i].indexOf(true));
```
- 각 행마다 한 개의 퀸만 배치 가능
- 조건에 부합하지 않는 경우 즉시 이전 상태로 복귀
```javascript
board[row][col] = true; // 퀸 배치
dfs(row + 1); // 다음 행 탐색
board[row][col] = false; // 백트래킹
```
1. 검증 범위 축소
- 아직 퀸을 놓지 않은 아래쪽 행은 검사하지 않음
- 이전에 놓은 퀸들과의 충돌만 검사
2. 대각선 체크 효율화
- 절댓값을 사용한 간단한 수식으로 대각선 체크
- 기존 4번의 반복문을 하나의 조건문으로 축소
백트래킹을 사용해 최적화함. 최악은 O(N!)이지만, 조건에 부합하면 복잡도 낮아짐
```
1. (0,0) 위치에 퀸 배치 시도
2. 가능하면 다음 행으로 이동
3. 불가능한 경우 발견 시 이전 상태로 복귀 …
```
> [태연] 250217

- Backjoon/250218_Dance_Dance_Revolution/choiseona.js
> [선아] 250218 

- Backjoon/250218_Dance_Dance_Revolution/ssum1ra.py
- 문제 이슈 넘버: #47 
- 3차원 dp 배열 활용
> [미라] 250218

- Backjoon/250219_치킨_배달/ssum1ra.py
- 문제 이슈 넘버: #52 
- 시간 복잡도 O(N^M) 
- abs(x1 - x2) + abs(y1 - y2)
> [미라] 250219

- Backjoon/250219_치킨_배달/dbjoung.js
- 문제 이슈 넘버: #52 
- 집에서 가장 가까운 치킨집까지의 거리가 치킨거리.
- 모든 집의 치킨거리를 합하면 도시의 치킨거리.
- M곳의 치킨집만 남겼을 때, 도시의 치킨거리의 최솟값 구하기.
- 도시 크기는 최대 2500, 치킨집 개수는 최대 13, 일반 집 개수는 최대 100
- M곳의 치킨집만 남겨야 하므로, 최대 <sub>13</sub>C<sub>M</sub> 중 도시 치킨거리가 가장 짧은 경우를 알아내면 될 것이다.
- dfs를 활용해 조합을 맞춰준다.
- 탈출조건을 잘 설정해 시간복잡도를 줄여준다.
1. 선택한 치킨집이 M개를 넘으면 return
2. 더이상 M개의 치킨집을 선택할 수 없는 상태이면 해당 루트 가지치기
3. 현재 루트에서 이미 선택한 치킨집은 재선택하지 않도록 방문 배열 설정
- 13C6 * 100 * 13 ...?
> [다솔] 250219

- Backjoon/250219_치킨_배달/choiseona.js
- 문제 이슈 넘버: #52 
조합 구한 후 최소 거리 구하기
> [선아] 250219

- Programmers/250220_가장_많이_받은_선물/ssum1ra.py
> [미라] 250220

- Programmers/250220_가장_많이_받은_선물/choiseona.js
> [선아] 250220

- Programmers/250223_도넛과_막대_그래프/ssum1ra.py
- 문제 이슈 넘버: #58
- indegree가 0, outdegree가 2 이상인 노드이다.
- 반드시 두 개 이상의 그래프가 존재하기 때문이다.
- 막대 그래프의 개수는 outdegree가 0인 노드의 개수와 같다.
- 8자 그래프의 개수는 indegree가 2 이상, outdegree가 2인 노드의 개수와 같다.
- 생성 노드가 해당 노드를 가리킬 수 있기 때문이다.
- 생성 노드의 outdegree - 막대 그래프의 개수 - 8자 그래프의 개수
> [미라] 250302

- Programmers/250223_도넛과_막대_그래프/choiseona.js
- 문제 이슈 넘버: #58 
- 문제에서의 제한 사항: 그래프는 2개 이상
- 들어오는 간선 0, 나가는 간선 2개 이상
- 나가는 간선 0 
- 생성한 정점에서 간선이 들어오므로 들어오는 간선 0일 때는 제외
- 들어오는 간선 2 이상, 나가는 간선 2 
- 들어오는 간선 2 이상인 이유: 생성한 정점에서 들어오는 간선 포함
- 생성한 정점의 나가는 간선 개수(그래프 개수) - 막대 개수 - 8자 개수
> [선아] 250302

- Backjoon/250219_치킨_배달/rhino-ty.js
- 문제 이슈 넘버: #52
- 완전탐색 + 최소값을 찾는 문제
- 조합 문제의 성격을 가짐
- DFS + 백트래킹으로 최적화 가능
- 도시 순회하며 치킨집, 집 좌표 저장
- DFS로 `M`개의 치킨집 선택 (조합)
- 선택된 치킨집들과 모든 집들 사이의 최소 거리 계산
```javascript
if (sum >= minResult) return Infinity;
```
```javascript
if (chiRes.length - index + count < M) return;
```
```javascript
function getChiResDistance(house, chiRes, selctedChiRes, minResult) {
let sum = 0;
for (const h of house) {
let min = Infinity;
for (const idx of selctedChiRes) {
min = Math.min(min, getDistance(h, chiRes[idx]));
}
sum += min;
if (sum >= minResult) return Infinity;
}
return sum;
}
```
```javascript
function dfs(index, count) {
if (count === M) {
minResult = Math.min(minResult, getChiResDistance(...));
return;
}
if (chiRes.length - index + count < M) return;
for (let i = index; i < chiRes.length; i++) { …
```
> [태연] 250219

- Programmers/250304_주사위_고르기/ssum1ra.py
- 문제 이슈 넘버: #67 
```py
for a_dices in combinations(range(n), n // 2):
b_dices = set(range(n)) - set(a_dices)
```
- `product(range(6), repeat=n // 2)` : 각 그룹의 주사위가 가질 수 있는 눈의 조합을 모두 생성한다.
- 예) 2번 반복한 경우 -> (0, 0), (0, 1), ...
- `sum(dice[i][j] for i, j in zip(a_dices, dice_cand))` : 각 주사위와 눈을 매칭한다.
- 예) (3번 주사위, 눈 0) + (5번 주사위, 눈 1)
- `bisect_left(b_score, a)` : 이분 탐색을 통해 a_score의 특정 점수보다 작은 값이 b_score 리스트에서 몇 개 있는지 센다.
- 즉, a_score의 특정 점수가 그룹 B의 점수들 중에서 몇 번 이길 수 있는지를 계산하는 방식이다.
- 모든 주사위의 조합을 고려한 경우 최악의 경우, 252 * 6^10 = 15,283,269,632
- 시간 초과
> [미라] 250304

- Backjoon/250305_타임머신/choiseona.js
- 문제 이슈 넘버: #70 
- 거리에 가중치 있어서 불가능
- 음수 순환은 어떻게 구할건데?? 
- 정점이 N개인 그래프가 주어졌을 때, N-1번 반복하면서 모든 간선을 확인하고 거리 테이블을 갱신 하는 방법으로 최단 거리 계산
- N-1번 반복해야 하는 이유는?
- 최단 경로가 최대 N-1개의 간선을 지나칠 수 있기 때문에 N-1번의 반복이 필요함 
- ex) 1 -> 6이 최단 경로일 수도, 1->3->2->5->4->6이 최단 경로일 수도 있음 
- 한 번 더(N번째) 모든 간선을 확인. 
- N번째 반복에서 거리 테이블이 더 짧은 거리를 찾아서 갱신돼야하면 negative cycle이 존재한다는 의미, 갱신 필요 없다면 negative cycle이 존재하지 않는다는 의미
- N번째 반복에서 갱신돼면 negative cycle인 이유는?
- N-1번의 반복 동안 모든 간선을 최대 N-1번 지나면서 최단 거리를 갱신하게 됨
- 만약 N번째 반복에서 거리 갱신이 일어난다면, 어떤 경로를 더 지나면서 계속 거리가 줄어들고 있다는 뜻임 
- 즉, 그 경로가 음수 사이클에 포함되어 있다는 것을 의미함. 
---
[참고 링크](https://uwallhyeok.tistory.com/230)
> [선아] 250305

- Backjoon/250306_평범한_배낭/ssum1ra.py
- 문제 이슈 넘버: #75
- 고려한 물건들이 (A, B, C, D)이고 최대 무게가 K일 때의 최대 가치는
1. D가 포함되지 않을 때, 고려한 물건들이 (A, B, C)이고 최대 무게가 K인 경우의 최대 가치와
2. D가 포함될 때, 고려한 물건들이 (A, B, C)이고 최대 무게가 (K - D의 무게)인 경우의 최대 가치 + D의 가치
- 중 큰 값이 된다.
- 2차원 dp 배열
- 행 (새롭게 고려하는 물건의 인덱스)  : A, AB, ABC, .... 
- 열 (최대 무게) : 1, 2, 3, ..., K
- dp[N][K]가 최종적으로 구하고자 하는 최대 가치가 된다.
> [미라] 250306

- Programmers/250309_n+1_카드게임/ssum1ra.py
- 문제 이슈 넘버: #79
- 구현 문제
**a 배열** : 손에 있는 카드
**b 배열** : 가져올 가능성이 있는 카드 (후보 카드)
매 라운드마다 b배열에 카드 두 장을 추가한다.
1) a 배열만 활용하여 n + 1을 만들어 낼 수 있는 경우, pass
2) a 배열만으로 n + 1을 만들어 내지 못하는 경우, b 배열에서 카드를 가져온다. (가져오는 개수만큼 코인 소모) 
> 후보 카드는 이후에 코인을 소모할 때 선택해도 괜찮다.
결과적으로, a와 b 배열을 모두 활용해도 n+1을 만들 수 없거나 코인이 음수가 되면 라운드 종료
> [미라] 250309

- Backjoon/250306_평범한_배낭/choiseona.js
> [선아] 250306

- Softeer/20250205_징검다리2/kwaksj329.js
- Softeer/20250205_출퇴근길/kwaksj329.js
- 문제 이슈 넘버: #16 
증가 LIS + 감소 LIS 구한뒤 최대가 되는 곳 찾는 방법으로 시도했으나 시간초과 문제로 `getLISArray` 에서 이진탐색을 실행하도록 함
- `lis`배열은 현재까지 만든 가장 작은 값들의 증가수열 유지
- `lengths 배열`은 각 위치에서 끝나는 증가수열의 최대 길이 저장
```
[3, 2, 4, 5, 1]
// lis = [2]  (3을 2로 교체)
// lengths = [1, 1]  (2의 위치에서 증가수열 길이는 1)
// lis = [2, 4]  (뒤에 추가)
// lengths = [1, 1, 2]  (4의 위치에서 증가수열 길이는 2)
// lis = [2, 4, 5]  (뒤에 추가)
// lengths = [1, 1, 2, 3]  (5의 위치에서 증가수열 길이는 3)
// lis = [1, 4, 5]  (2를 1로 교체)
// lengths = [1, 1, 2, 3, 1]  (1의 위치에서 증가수열 길이는 1)
```
- 문제 이슈 넘버: #17
> [수정] 250205

- Programmers/250304_주사위_고르기/rhino-ty.js
- 문제 이슈 넘버: #67 
이 문제는 주사위 게임에서 승리 확률을 최대화하는 주사위 선택 문제입니다.
- A와 B가 주사위를 n/2개씩 나눠 가짐
- 각자 주사위를 굴려 나온 숫자의 합이 큰 쪽이 승리
- A가 승리할 확률이 최대가 되도록 주사위를 선택해야 함
처음에는 단순 완전탐색 접근법을 생각했는데, 시간복잡도를 계산해보니 너무 커져서 고민이 됐습니다.
- 주사위 조합 선택 : C(10,5) ≈ 252가지
- 각 선택에 대한 주사위 결과:  6^5 × 6^5 ≈ 6천만 가지
- 총 연산 수 : 약 150억 번!
이는 시간 초과를 초래할 수 있어 DP를 활용한 최적화가 필요했습니다.
여기서 합 분포는 다시 말해, 주사위의 여러 숫자를 합했을 때, 나오는 횟수를 지칭합니다.
1. **주사위 조합 생성**
- 백트래킹을 활용해 A가 선택할 수 있는 모든 주사위 조합을 생성
- 전체 n개 주사위에서 n/2개를 선택하는 모든 경우의 수 구함
2. **DP를 활용한 합 분포 계산**
- 각 주사위 조합에 대해 가능한 모든 합의 분포를 DP로 계산
- 첫 번째 주사위에 대한 초기 분포 생성 후 나머지 주사위를 하나씩 추가하며 분포 갱신
- 기존 분포의 모든 값에 새 주사위의 각 면을 더해 새로운 분포 계산
- 이 방식으로 모든 가능한 주사위 결과를 직접 시뮬레이션하지 않아도 됨
3. **승률 계산**
- A와 B의 합 분포를 비교해 승률 계산
- A의 모든 가능한 합과 B의 모든 가능한 합을 비교
- A의 합 > B의 합인 경우의 수 / 전체 경우의 수 = 승률
4. **최적 조합 선택**
- 승률이 가장 높은 …
> [태연] 250304

- Backjoon/250305_타임머신/rhino-ty.js
- 문제 이슈 넘버: #70 
- **문제 요약**: N개의 도시와 M개의 버스 노선이 있을 때, 1번 도시에서 다른 모든 도시로 가는 최단 시간을 구하는 문제
- **특이사항**: 버스 노선의 소요 시간이 음수일 수 있으며, 음수 사이클이 있는 경우에는 `-1`을 출력해야 함
다익스트라 알고리즘은 음수 가중치가 있는 경우 정확한 결과를 보장하지 않기 때문에, 음수 가중치를 처리할 수 있는 벨만-포드 알고리즘을 사용했습니다.
1. **최단 거리 배열 초기화**
- 1번 도시는 시작점이므로 `distance[1] = 0`으로 설정
- 나머지 도시는 `Infinity`로 초기화
2. **벨만-포드 알고리즘 실행**
- 모든 간선에 대해 N-1번 반복하여 최단 거리 갱신
- 각 반복에서 `distance[to] = min(distance[to], distance[from] + time)` 연산 수행
3. **음수 사이클 검사**
- N-1번의 반복 후에도 더 짧은 경로가 발견되면 음수 사이클이 존재
- 음수 사이클이 발견되면 `-1` 출력
4. **결과 출력**
- 음수 사이클이 없는 경우, 2번 도시부터 N번 도시까지의 최단 거리 출력
- 도달할 수 없는 도시(거리가 `Infinity`인 경우)는 `-1` 출력
- 벨만-포드 알고리즘: O(N*M), N은 도시의 수, M은 버스 노선의 수
- 총 시간 복잡도: O(N*M)
1. **벨만-포드 알고리즘의 원리**
- 다익스트라와 달리 모든 간선을 반복적으로 검사하여 최단 경로 갱신
- N-1번 반복은 최대 N-1개의 간선을 통과하는 경로가 존재할 수 있기 때문 …
> [태연] 250305

- Programmers/250310_봉인된_주문/ssum1ra.py
- 문제 이슈 넘버: #83 
```py
n = 723
n -= 1  # n = 723 - 1 -> n = 722
n % 26  # 722 % 26 = 722 - (26 * 27) = 722 - 702 = 20 -> 'u' (나머지가 20이므로 'u')
n //= 26  # n = 722 // 26 -> n = 27
n -= 1  # n = 27 - 1 -> n = 26
n % 26  # 26 % 26 = 0 -> 'a' (나머지가 0이므로 'a')
n //= 26  # n = 26 // 26 -> n = 1
n -= 1  # n = 1 - 1 -> n = 0
n % 26  # 0 % 26 = 0 -> 'a' (나머지가 0이므로 'a')
n //= 26  # n = 0 // 26 -> n = 0 (반복 종료)
```
- 매번 1을 빼는 이유
- 예 ) 1(26) -> a, 2(26) -> b ..., 25(26) -> y, 10(26) -> z, 11(26) -> aa...
- 금지된 주문이 구해진 주문보다 앞선 경우(n보다 작거나 같으면), n을 1 증가시킨다.
> [미라] 250310

- Programmers/250310_봉인된_주문/choiseona.js
- 문제 이슈 넘버: #83 
1. 알파벳(26진수)를 숫자(10진수)로 변환 후 오름차순 정렬
2. 요소 제거했을 때 구해야하는 위치(10진수) 구하기
3. 2단계에서 구한 위치(10진수)를 알파벳(26진수)으로 변환
> [선아] 250310

- Programmers/250312_지게차와_크레인/ssum1ra.py
- 문제 이슈 넘버: #102 
- 문자열의 길이가 2인 경우, 해당하는 컨테이너 조건없이 제거
- 문자열의 길이가 1인 경우,
- 해당하는 컨테이너가 외곽에 위치하는 경우(x = 0 or y=0 or x = 행의 개수 - 1 or y = 열의 개수 - 1) 제거
- 해당하는 컨테이너가 내부에 위치하는 경우
- 해당 컨테이너를 둘러싼 모든 컨테이너의 위치를 확인한다.
- 둘러싼 컨테이너의 위치를 통해 지게차가 접근할 수 있는지 확인하여 제거 (bfs 활용)
- 주의 : 바로 제거해서는 안되고 루프가 종료된 뒤, 업데이트해야 한다. (문제 기준)
- 상, 하, 좌, 우로 이동하며 빈 위치인 경우에만 이동
- 방문한 위치 중 하나라도 외곽에 위치한다면, 지게차 접근 가능
- 시간복잡도 고려 안 함
- 매번 지게차 접근 여부를 확인하지 않고 캐싱
- 1시간
> [미라] 250312

- Programmers/250313_퍼즐_게임_챌린지/ssum1ra.py
- 문제 이슈 넘버: #108 
- 모든 level 순회
- 시간 초과
- 이분 탐색을 통해 level 범위를 좁혀간다.
- 1시간 20분?
- 완탐으로 풀기 전에 시간복잡도를 먼저 계산해볼 걸 그랬다. 시간만 더 씀.
> [미라] 250313

- Programmers/250316_충돌위험_찾기/ssum1ra.py
- 문제 이슈 넘버: #113 
- 로봇마다 지나는 점 구하기
- 특정 시간에 동일한 점을 지난다면 +1
- 1시간 20분 정도
- 차근차근 풀어야 하는 문제이긴 한데 너무 오래 걸린듯
> [미라] 250316

- Programmers/250317_석유_시추/ssum1ra.py
- 문제 이슈 넘버: #117 
- 열을 기준으로 반복하며 체크
- 매번 bfs를 통해 석유 덩어리 크기 체크 (중복 연산 빈번)
- 시간 초과
- 석유 덩어리 영역을 라벨링
- 첫 번째 풀이 : 20분 정도?
- 두 번째 풀이 : 추가 20분
> [미라] 250317

- Programmers/250312_지게차와_크레인/choiseona.js
- 문제 이슈 넘버: #102 
- 인접한 빈 공간이 **외부와 연결된** 공간이면 제거 
- 컨테이너 바로 제거
- 2시간
> [선아] 250312

- Programmers/250316_충돌위험_찾기/choiseona.js
- 문제 이슈 넘버: #113 
1. 최단 경로 이동 (r좌표 우선)
- 행(row) 좌표를 먼저 이동한 후 열(column) 좌표 이동
- 한 번에 한 칸씩 이동
2. 로봇의 위치와 시간 추적
- 각 로봇의 이동 경로를 시간별로 기록 key: `${row},${col},${time}` value: `로봇 개수`
- 같은 위치, 같은 시간에 여러 로봇이 있는지 확인
3. 위험 상황 카운트
- 같은 위치, 같은 시간에 2대 이상의 로봇이 있는 경우를 찾음
- 각 위험 상황은 한 번만 카운트
> [선아] 050316

- Programmers/250318_아날로그_시계/ssum1ra.py
- 문제 이슈 넘버: #121
- 360/N -> N초만에 한바퀴 돈다.
- 초침 : 360/60 = 6도 
- 분침 : 360/(60*60) = 1/10도 
- 시침 : 360/(60*60*12) = 1/120도
- 현재 초침이 시침/분침에 비해 뒤쳐지다가 1초 뒤 앞지른 경우 -> 만났다
- 시침과 분침 초침이 모두 만나는 경우
- 자정 or 정오 
- 무의미.. 30분 고민하다 그냥 구글링했어여
> [미라] 250318

- Programmers/250319_택배_배달과_수거하기/ssum1ra.py
- 문제 이슈 넘버: #123 
- d_cnt : 배달해야 할 택배
- p_cnt : 수거해야 할 택배
- 그 위치까지 방문해야한다
- 방문하고 나면 cap만큼 배달하거나 수거해야하는 택배가 줄어든다.
- 이때, 음수가 된다면 여유분이 되어 다음 위치는 왕복으로 방문하지 않을 수도 있다. (즉, 이번 방문에서 같이 배달/수거 해간다.)
- 1시간 정도 풀다가 시간초과 해결 못 하고 답 봄
- 그리디 너무 어려워요...
> [미라] 250319

- Programmers/250313_퍼즐_게임_챌린지/dbjoung.js
- 문제 이슈 넘버: #108 
- 1시간 12분
- n개의 퍼즐.
- 현재 퍼즐 난이도 diff, 소요 시간 time_cur, 이전 퍼즐 소요시간 time_prey, 내 숙련도 level
- diff <= level 이면 퍼즐이 틀리지 않고, time_cur 만큼의 시간을 사용하여 해결
- diff > level 이면 퍼즐을 총 diff-level 번 틀림. 퍼즐을 틀릴 때마다 time_cur만큼의 시간을 사용 & time_prev 만큼의 시간을 사용해 이전 퍼즐을 다시 풀고 와야 함.
- 제한시간(limit) 있음. 제한 시간 내에 퍼즐을 모두 해결하기 위한 숙련도의 최솟값 구하기
- dp + 이분탐색 
- 레벨의 최솟값은 1, 최대값은 diffs 배열의 최대값이다.
- left = 1, right = diffs 배열의 최대값을 넣어 level을 이분탐색. 
- 푼 시간 <= limit 이면 lev를 더 낮추는 방향으로.
- 계산 안해봄
> [다솔] 250313

- Programmers/250319_택배_배달과_수거하기/dbjoung.js
- 문제 이슈 넘버: #123 
- 약 2시간
- 일렬로 나열된 n개의 집에 택배 배달.
- 모두 크기가 같은 재활용 택배 상자에 담아 배달. 동시에 빈 재활용 택배 상자는 수거.
- 트럭에 재활용 상자 최대 cap개 실을 수 있음
- dp는 메모리 초과 발생할 것 같음
-  무조건 먼 집까지 방문했다가 돌아오며 수거하는게 이득.
-  1. n번째 집부터 역순회하며 첫번째 실을 박스 개수를 구한다.
-  2. n번째 집부터 역순회 하며 비워야 할 박스 개수를 구한다.
-  1-2 반복
- del 과 pick 변수에 각각 총 배달해야 할 개수랑 수거해야할 개수를 저장
- 배송 및 수거 작업 하면서 위 변수값 변경
- for문으로 종료 체크하지 않고, del과 pick이 모두 0이 된 경우 작업 종료하도록 하여 시간 복잡도 개선
- 매 while문 반복마다 farHouse 값 갱신
- if (del>0), if(pick>0) 조건으로 배달 혹은 수거가 남았을 경우만 해당 for문 돌게 하기
- 계산 x. 하지만 시간복잡도 고려가 필요한 문제였다.
> [다솔] 250319

- Programmers/250312_지게차와_크레인/rhino-ty.js
- 문제 이슈 넘버: #102
이 문제는 물류창고에 있는 컨테이너를 두 가지 방식으로 출고하는 로직을 구현하는 것입니다.
1. **지게차 작업**(1글자 요청): 외부와 연결된 컨테이너만 제거
2. **크레인 작업**(2글자 요청): 해당 종류의 모든 컨테이너 제거
핵심은 '**외부와 연결된**' 컨테이너를 정확히 판별하는 것입니다. 컨테이너가 제거될 때마다 다른 컨테이너의 '**외부 연결**' 상태가 변할 수 있기 때문에 동적인 문제입니다.
1. **2차원 배열로 창고 상태 표현**: 문자열 배열인 `storage`를 2차원 배열로 변환
2. **요청 처리**
- 크레인 요청(2글자): 해당 종류의 모든 컨테이너 한번에 제거
- 지게차 요청(1글자): 외부와 연결된 컨테이너만 제거
3. **외부 연결 확인** BFS 알고리즘을 활용하여 컨테이너가 외부와 연결되었는지 확인
처음에는 외부 연결을 단순히 "주변에 null이 있는지"로 판단했습니다.
```javascript
// 잘못된 접근
function isExternalContainer(containerMatrix, n, m) {
// 가장자리 확인
if (n === 0 || n === containerMatrix.length - 1 || 
m === 0 || m === containerMatrix[n].length - 1) {
return true;
}
// 주변에 빈 공간이 있는지 확인
if (!containerMatrix[n-1][m] || !containerMatrix[n+1][m] || 
!containerMatrix[n][m-1] || …
```
> [태연] 250312

- Programmers/250317_석유_시추/rhino-ty.js
- 문제 이슈 넘버: #117 
- 2차원 격자에서 석유는 상하좌우로 연결된 '1'로 표시됨
- 시추관은 열 하나를 수직으로 관통함
- 시추관이 석유 덩어리 일부를 지나면 전체 덩어리를 얻을 수 있음
목표는 최대 석유량을 얻을 수 있는 시추관 위치 찾는 것입니다.
1. **그래프 탐색(BFS)을 통한 석유 덩어리 식별**
- 석유 덩어리는 상하좌우로 연결된 '1'들의 집합이므로 BFS를 사용해 각 덩어리 식별
- 이미 방문한 석유 위치는 다시 탐색하지 않도록 방문 여부 체크
2. **각 열별 석유량 계산**
- 각 석유 덩어리를 BFS로 탐색하면서, 해당 덩어리가 어떤 열에 영향을 미치는지 기록
- 탐색이 완료되면 덩어리의 크기를 계산하고, 영향을 받는 모든 열에 해당 크기 더하기
3. **최대 석유량 찾기**
- 모든 석유 덩어리 탐색이 완료된 후, 각 열별 석유량 중 최대값 찾아 반환
- **방문 체크**를 통해 각 석유 위치를 한 번만 탐색해 중복 계산 방지
- 각 석유 덩어리의 **크기를 한 번만 계산**하고 여러 열에 적용, 효율성 증대
- 전체 탐색: O(N*M) - 각 위치를 최대 한 번씩만 방문
- 각 열에 석유량 추가: O(M) - M은 열의 개수
- 전체 시간 복잡도: O(N*M)
- visited 배열: O(N*M)
- oilByColumn 배열: O(M)
- BFS 큐: 최악의 경우 O(N*M)
- 전체 공간 복잡도: O(N*M)
> [태연] 250317

- Programmers/250319_택배_배달과_수거하기/rhino-ty.js
- 문제 이슈 넘버: #123
이 문제는 물류창고에서 출발하여 각 집에 택배를 배달하고 빈 상자를 수거하는 최적의 경로를 찾는 문제입니다. 
트럭은 최대 `cap`개의 상자만 실을 수 있으며, 모든 배달과 수거를 완료하기 위한 최소 이동 거리를 구해야 합니다.
1. **그리디(Greedy) 알고리즘**
- 가장 먼 집부터 처리하는 것이 효율적인 이유: 가장 먼 집까지 왕복한다면, 그 경로 상의 다른 집들은 추가 이동 거리 없이 처리할 수 있기 때문
- 각 왕복 여정에서 트럭 용량 내에서 최대한 많은 배달/수거 처리
2. **최적화 과정**
- 첫 번째 구현: 매 반복마다 전체 배열 스캔하여 가장 먼 집 찾기
- 두 번째 구현: `lastIdx` 변수로 이미 처리한 높은 인덱스는 다시 검사하지 않도록 최적화
- 최종 구현: 배달과 수거 각각의 마지막 위치를 독립적으로 추적하는 방식으로 최적화
```javascript
while (true) {
// 배달할 물건이 있는 가장 먼 집 찾기 - 매번 전체 배열 탐색
for (let i = n - 1; i >= 0; i--) { ... }
// 수거할 물건이 있는 가장 먼 집 찾기 - 매번 전체 배열 탐색
for (let i = n - 1; i >= 0; i--) { ... }
// 배달/수거 처리
}
```
- 문제점: 매 반복마다 전체 배열을 스캔하여 O(n²) 시간 복잡도
- 일부 테스트 케이스 통과하나 대규모 데이터셋에서 시간 초과 발생
```javascript
let lastIdx = n - 1;
while (true) {
// lastIdx부터 탐색 시작 …
```
> [태연] 250319

- Programmers/250320_양궁대회/ssum1ra.py
- 문제 이슈 넘버: #126
- dfs 활용
- 현재 점수를 라이언이 얻을지 말지 선택
- 1시간 반 쯤...?
> [미라] 250320

- Programmers/250317_석유_시추/choiseona.js
- 문제 이슈 넘버: #117 
1. **BFS를 사용하여 석유 덩어리 그룹화**  
- land를 순회하며 방문하지 않은 석유를 발견하면 BFS 실행  
- BFS를 통해 연결된 석유 좌표를 탐색하고, 각 위치에 `{key, size}` 저장  
- `key`는 덩어리의 고유 ID, `size`는 해당 덩어리의 크기  
2. **각 열(column)별 최대 석유량 계산**  
- 각 열을 순회하면서, 해당 열에 있는 서로 다른 `key`들의 `size` 합산  
- 가장 큰 합을 가진 열의 값을 반환  
1. **BFS를 사용하여 석유 덩어리 탐색**  
- 방문하지 않은 석유를 발견하면 BFS 실행  
- BFS를 통해 연결된 석유 좌표들을 찾아 반환  
2. **각 열(column)별 석유량 계산**  
- BFS로 찾은 석유 덩어리의 모든 열을 `Set`에 저장하여 중복 제거  
- 해당 열에 석유 덩어리 크기만큼 석유량 누적  
3. **최대 석유량이 있는 열 찾기**  
- `seokU` 배열에서 최대값 반환  
---
- 2:55 시작
- 3:48 시간초과
- 4:03 완료
> [선아] 250317

- Programmers/250321_수식_복원하기/choiseona.js
- 문제 이슈 넘버: #130 
- 시작: 5:10, 
- 16-21번 오답: 7:32
- 해결: 7:49 
- 총: 2시간 39분 
1. 파싱/계산과 최소 진법 결정 
- 각 수식을 파싱하면서 동시에 모든 진법(2~9)에 대한 계산 수행 (원래는 가능한 진법에 대해 계산하는 것이 효율적인 것 같아 분리하였으나 2-9 진법만 가능하다는 점과 코드  가독성을 고려하여 통합) 
- array 배열에 [leftString, operator, rightString, result, resultString] 형태로 저장
- 모든 수식에서 등장하는 가장 큰 숫자 + 1로 최소 진법 결정
3. 유효한 진법 필터링
- minBase 미만의 진법은 유효한 진법에 대한 결과값 필터링에서 제외
- array 배열을 필터링하여 모든 수식의 결과가 일치하는 진법만 선택
- "X" 표시는 어떤 결과값도 허용
5. 결과 도출 로직
- 배열의 resultString이 "X"인 것만 결과에 추가 
- 진법이 하나로 특정되면 해당 진법의 result 사용
- 진법이 여러 개인 경우:
- 모든 진법에서 동일한 결과가 나오면 result를 answer에 push 
- 진법에 따라 다른 결과가 나오면 result를 "?" 로 교체 후 answer에 push
> [선아] 250321

- Programmers/250314_홀짝트리/ssum1ra.py
- Programmers/250321_수식_복원하기/ssum1ra.py
- 문제 이슈 넘버: #130 
- 숫자 중 가장 큰 값을 찾는다. 
- (가장 큰 수 + 1) ~ 9진법이 후보
- 답이 있는 표현식을 분석한다.
- 후보 진법으로 모든 표현식을 계산 했을 때, 정답과 모두 같다면 -> 후보
- 모든 후보 진법에서 결과가 같다면, 결과를 포함한 채 리턴
- 아니라면, '?' 리턴
- 2시간 넘게.. ㅜㅜ
- 문제 이슈 넘버: #112
- 루트를 바꿔가며 bfs 탐색
- 시간 초과
- 유니온 파인드 활용, 트리 분리하기
- [노션 참고](https://inquisitive-beret-c36.notion.site/Union-Find-Algorithm-1bd55cd93d4f8012b5cbd5ef4d2f03e0?pvs=74)
- 홀짝 트리의 경우, 노드의 수와 노드의 차수가 모두 홀/홀, 짝/짝인 노드가 하나여야 함. 이 노드가 루트가 된다.
- 다른 노드들은 input을 빼고 자식만 생각해야함.
- 즉, 다른 노드들은 노드의 수와 노드의 차수가 홀/짝 이거나 짝/홀이어야 한다.
- 역홀짝 트리의 경우, 노드의 수와 노드의 차수가 모두 홀/짝, 짝/홀인 노드가 하나여야 함. 이 노드가 루트가 된다.
- 다른 노드들은 input을 빼고 자식만 생각해야함.
- 즉, 다른 노드들은 노드의 수와 노드의 차수가 짝/짝 이거나 홀/홀이어야 한다.
> [미라] 250321

- Programmers/250324_비밀_코드_해독/ssum1ra.py
- 문제 이슈 넘버: #135 
- dfs 활용
- 모든 ans와 일치하는 비밀 코드 개수 구하기  
- 25분 정도
> [미라] 250324

- Programmers/250324_비밀_코드_해독/choiseona.js
- 문제 이슈 넘버: #135 
- 시작: 14:10
- 끝: 14:31
- 총 21분 
**1. 가능한 모든 조합 생성**
- 1부터 n까지의 모든 숫자 중에서 5개를 선택하는 모든 조합을 생성
- 재귀적 방식을 활용해 조합을 구합니다. 현재 요소를 선택하고 나머지 요소들에서 남은 개수를 선택하는 방식으로 진행 
**2. 조건 검증**
- 생성된 각 조합에 대해 주어진 모든 쿼리를 검증
- 각 쿼리 배열에 있는 요소들 중 현재 조합에 포함된 요소의 개수를 계산
- 계산된 개수가 정답 배열의 값과 일치하는지 확인
**3. 정답 계산**
- 모든 쿼리 조건을 통과한 조합의 개수를 카운트
- 하나의 쿼리라도 조건을 만족하지 않으면 해당 조합은 가능한 비밀코드가 될 수 없음
> [선아] 250324

- Programmers/250320_양궁대회/rhino-ty.js
- Programmers/250321_수식_복원하기/rhino-ty.js
- 문제 이슈 넘버: #126 
`라이언이 어피치를 가장 큰 점수 차이로 이기기 위한 화살 배치`를 찾는 문제입니다. 문제를 해결하기 위해 다음과 같은 과정으로 접근했습니다.
처음에는 문제의 조건이 너무 많아서 세밀하게 분석했습니다.
- 화살은 정확히 n발을 모두 사용해야 함
- 점수는 "더 많은 화살을 맞힌 선수"가 가져가며, 동점일 경우 어피치가 점수를 가져감
- 라이언이 이길 수 없는 경우 [-1] 반환
- 같은 점수 차이라면 낮은 점수에 더 많은 화살을 배치한 경우를 선택
문제 특성상 모든 경우의 수를 탐색해야 하므로 DFS(깊이 우선 탐색)를 사용하기로 결정했습니다. 화살 수가 최대 10개, 점수대가 11개로 제한돼 있어 완전 탐색으로도 시간 내에 해결 가능합니다.
DFS 함수는 다음과 같은 로직으로 구현했습니다.
- 매개변수: 현재 점수대 인덱스(`idx`), 남은 화살 수(`leftArrows`)
- 각 점수대에서 두 가지 선택을 시도
1. 해당 점수를 획득하기 위해 어피치보다 1발 더 많이 쏘기
2. 해당 점수대를 포기하고 화살을 쏘지 않기
- 모든 점수대를 확인했거나 화살을 모두 사용했을 때 점수 계산 및 비교
라이언이 이기는 경우 중에서도
- 점수 차이가 가장 큰 경우를 선택
- 같은 점수 차이라면 `isLowerScoreBetter` 함수를 통해 낮은 점수에 더 많은 화살을 배치한 경우를 우선시
화살 배치를 시도한 후 다시 원래 상태로 복원(백트래킹)해 메모리를 효율적으로 사용하고, 모든 가능한 조합을 빠짐없이 탐색할 수 있게 했습니다.
1. **점수 계산 로직**: 양궁 규칙에 따라 각 …
> [태연] 250320

- Programmers/250324_비밀_코드_해독/rhino-ty.js
- 문제 이슈 넘버: #135
비밀 코드(5개의 오름차순 정수)를 맞추기 위해 m번의 시도를 한 결과, 비밀 코드로 가능한 모든 조합의 개수를 찾는 문제입니다.
이 문제는 제한 조건이 n ≤ 30으로 작기 때문에, 완탐과 백트래킹을 활용한 DFS 방식으로 접근했습니다.
1. 1부터 n까지의 숫자 중 5개를 선택하는 모든 가능한 조합 생성
2. 각 조합이 주어진 모든 시도(`q`)와 응답(`ans`)을 만족하는지 확인
3. 모든 조건을 만족하는 조합 개수 계산
재귀 함수를 이용해 모든 가능한 5개 숫자 조합을 효율적으로 생성합니다. 백트래킹은 `current.pop()` 부분에서 이루어지며, 이를 통해 하나의 조합을 완성한 후 이전 상태로 돌아가 다른 조합을 시도 가능합니다.
```javascript
function generateCombis(current, start) {
if (current.length === 5) {
// 조건 확인 및 결과 카운팅
return;
}
for (let i = start; i <= n; i++) {
current.push(i);
generateCombis(current, i + 1);
current.pop(); // 백트래킹 부분
}
}
```
각 조합에 대해, 모든 시도와 응답을 만족하는지 확인합니다. 각 시도에서 선택한 5개 숫자 중 비밀 코드에 포함된 숫자의 개수가 `ans`와 일치해야 합니다.
```javascript
function isValidCode(q, ans, code) {
for (let i = 0; i < q.length; i++) {
// 현재 시도의 …
```
> [태연] 250324

- Programmers/250325_표현_가능한_이진트리/ssum1ra.py
- 문제 이슈 넘버: #141
- 10진수 2진수로 만들기
- padding 붙이기
- 트리가 나올 수 있는 이진수의 길이 : 1, 3, 7, 15, ...
- 두 트리가 합쳐지고 루트가 더해진 값이 깊이가 1 증가한 트리가 되기 때문이다.
- next = current * 2 + 1
- 이진 트리 체크
- 루트를 확인한다.
- 1이라면, 통과
- 0이라면, 모든 자식이 0인 경우에만 통과 
- 트리를 나누어서 작은 트리의 루트를 확인한다.
- 40 ~ 50분?
> [미라] 250325

- Programmers/250324_비밀_코드_해독/dbjoung.js
- 문제 이슈 넘버: #135 
- 40분 (39분 39초)
- dfs 조합
- 30C5 * (10 * 5 * 5) = 35,626,500
> [다솔] 250324

- Programmers/250328_등산코스_정하기/ssum1ra.py
- 문제 이슈 넘버: #151 
- 다익스트라 알고리즘 활용
- 출발 노드에서 모든 노드까지의 최소 intensity를 구한다. 
- [노션 참고](https://inquisitive-beret-c36.notion.site/1c455cd93d4f8088874fce29eb2b707d)
> [미라] 250328

- Programmers/250327_파괴되지_않은_건물/choiseona.js
- 문제 이슈 넘버: #146 
- 의미 없음 
1. **skill 돌면서 누적합 배열 누적하기**
```
n 0 -n
0 0 0
-n 0 n
```
2. **1에서 얻은 결과를 누적합하기** 
- 왼쪽에서 오른쪽으로 누적합
- 위에서 아래로 누적합 
3. **결과 구하기**
- 2에서 얻은 결과 배열을 돌면서 board값과 더한 후 0초과인 것만 count 
[카카오 해설](https://tech.kakao.com/posts/488#%EB%AC%B8%EC%A0%9C-6-%ED%8C%8C%EA%B4%B4%EB%90%98%EC%A7%80-%EC%95%8A%EC%9D%80-%EA%B1%B4%EB%AC%BC)
> [선아] 250327

- Programmers/250328_등산코스_정하기/choiseona.js
- 문제 이슈 넘버: #151 
- 의미 없음 
1. 최소 힙(우선순위 큐)을 구현하여 항상 가장 작은 intensity를 가진 경로부터 탐색
2. 일반적인 다익스트라와 달리 경로의 합이 아닌 **경로 중 최대 가중치의 최솟값**을 구함
3. 모든 출입구에서 동시에 탐색을 시작하여 각 지점까지의 최소 intensity를 계산
4. 산봉우리에 도달하면 더 이상 탐색하지 않음 (산봉우리는 경로의 끝이어야 함).
5. 계산된 최소 intensity 중 가장 작은 값을 가진 산봉우리를 선택하되, 같은 intensity를 가진 경우 번호가 작은 산봉우리를 선택
> [선아] 250328

- Programmers/250306_미로_탈출_명령어/choiseona.js
- 문제 이슈 넘버: #143 
- 시작: 8:20
- 끝: 9:08
- 총 48분 
1. **초기 조건 검사**
- 최단 거리와 이동 횟수(k)의 홀짝성 검사: 두 값의 홀짝성이 다르면 도달 불가능
- "왔다갔다" 2번의 이동으로 홀수면 홀수, 짝수면 짝수로 유지되기 때문 
- 최단 거리가 이동 횟수보다 크면 도달 불가능
2. **그리디 방식의 경로 탐색**
- 사전순(d→l→r→u) 우선순위에 따라 매 단계에서 최선의 선택
- 각 이동은 다음 조건을 만족해야 함:
* 격자 범위 내에 있을 것
* 현재 위치에서의 최단 거리가 남은 이동횟수보다 작거나 같아야함 
3. **종료 조건**
- k번 이동 완료 후 경로 반환
- 중간에 목적지에 도달하더라도 k번을 채울 때까지 이동 계속
> [선아] 250326

- Programmers/250331_순위_검색/choiseona.js
- 문제 이슈 넘버: #155 
- 의미 없음 
- 각 지원자 정보에 대해 가능한 모든 조건 조합을 생성
- 각 조건(언어, 직군, 경력, 소울푸드)마다 실제 값과 와일드카드('-')를 고려하여 총 16가지 조합 생성
- 각 조합을 키로 하는 맵을 만들고, value로 지원자의 점수를 배열로 저장
- 이후 이진 탐색을 위해 각 점수 배열을 오름차순으로 정렬
- 정렬된 배열에서 특정 점수 이상인 첫 번째 요소의 인덱스를 찾기 위해 이진 탐색 알고리즘 사용 
- 이 인덱스를 사용하여 기준 점수 이상인 지원자의 수를 효율적으로 계산
- 각 쿼리를 파싱하여 조건 조합과 기준 점수를 추출
- 해당 조건 조합의 키가 맵에 존재하면, 이진 탐색으로 기준 점수 이상인 지원자 수를 계산
- 조건 조합이 맵에 없으면 0을 push
> [선아] 250331

- Programmers/250331_순위_검색/ssum1ra.py
- 문제 이슈 넘버: #155 
- dictionary 활용
- 지원자 정보를 바탕으로 만족할 수 있는 모든 조건을 키로 두고 점수를 값으로 둔다.
- 조건 4개 중 일부를 '-'로 대체하며 가능한 모든 조합을 만든다.
- 이미 존재하는 키라면, 점수 배열에 append한다.
- 문의 조건을 키 형태로 변환해 탐색한다.
- 해당 키가 존재하는 경우 점수 배열에서 이분 탐색을 이용해 타겟 점수 이상의 인원 수를 계산한다.
- 카카오 풀이 참고
> [미라] 250331

- Programmers/250401_교점에_별_만들기/ssum1ra.py
- 문제 이슈 넘버: #159 
- 교점 구하기
- 조합을 통해 두 선씩 검사
- 일반적인 교점 공식 활용
- A1x + B1y + E1 = 0, A2x + B2y + E2 = 0인 경우
- ![image](https://github.com/user-attachments/assets/0fe16d2a-3fdd-4fb2-8120-4a7b44320e65)
- 분모가 0이 되면, 평행 or 일치
- 40분쯤? -> 차분히 풀자 ㅜㅜ
> [미라] 250401

- Programmers/250402_양과_늑대/ssum1ra.py
- 문제 이슈 넘버: #163 
- dfs 활용
- 현재노드, 양의 수, 늑대의 수, 다음 방문할 수 있는 노드들을 매개변수로 둔다.
- 늑대의 수가 양의 수보다 많거나 같아진다면, 탐색 중단
- 양의 수가 많다면 최대 양의 수 갱신
- dfs를 호출하여 다음 노드 탐색
- 30분 동안 고민하다가 모르는 알고리즘 활용하는 문제일까봐 힌트봤는데 걍 dfs 쓰면 된다고 해서 활용해서 문제 품.
- 의미없지만 전체 풀이 시간은 1시간 정도...?
> [미라] 250402

- Programmers/250403_표_편집/ssum1ra.py
- 문제 이슈 넘버: #166 
- 각 행은 앞(prev)뒤(next)가 누군지 알고 있으면 된다.
```
0 <-> 1 <-> 2 <-> 3 <-> 4
```
- 2번 행을 삭제한다면? → 1번 행의 next를 3으로, 3번 행의 prev를 1로 바꿔주면 된다.
행 | prev | next
-- | -- | --
0 | -1 | 1
1 | 0 | 2
2 | 1 | 3
3 | 2 | 4
4 | 3 | -1
-> prev[2] = 1, next[2] = 3
-> 1의 next를 3으로 3의 prev를 1로 바꾼다.
-> 2는 삭제된 것처럼 보인다.
- node = 2, prev = 1, next = 3
- 1의 next를 2로, 3의 prev를 2로 복구한다.
- 이분 탐색 활용해서 풀었는데 효율성 테스트 통과 못함. (30분 소요)
- 삽입/삭제가 문제인거 같긴한데 어떻게 링크드 리스트로 구현할 지 감이 안 잡혀서 블로그 찾아봄.
- 의미없음...
> [미라] 250403

- Programmers/250325_표현_가능한_이진트리/rhino-ty.js
- 문제 이슈 넘버: #141 
이 문제는 주어진 숫자가 이진트리로 표현 가능한지 판별하는 문제입니다. 문제에서 제시한 이진트리의 **수 변환 규칙**을 역으로 적용하여 해결해야 합니다.
핵심은 아래와 같습니다.
1. 이진트리는 포화 이진트리 형태로 변환됨 (더미 노드 추가) => $2^n - 1$ 형태임([아래 패턴 분석](#패턴-분석)을 참고)
2. 노드를 왼쪽에서 오른쪽으로 살펴보며 이진수 생성
3. 실제 노드는 1, 더미 노드는 0으로 표시
4. 더미 노드(0)는 자식으로 실제 노드(1)를 가질 수 없음
포화 이진트리의 노드 수는 항상 $2^n - 1$ 형태가 됩니다.
- 높이 1: 1개 노드 ($2^1 - 1$)
- 높이 2: 3개 노드 ($2^2 - 1$)
- 높이 3: 7개 노드 ($2^3 - 1$)
- 높이 4: 15개 노드 ($2^4 - 1$)
따라서 이진수 표현의 길이도 $2^n - 1$ 형태여야 합니다!
1. **이진수 변환과 패딩**
- 주어진 숫자를 이진수로 변환
- 이진수 길이가 2^n - 1 형태가 되도록 앞에 0을 패딩 (`padStart`로 해도 되고 `'0'.repeat`방식으로 해도 되고)
- 패딩은 반복이나 로그를 사용해 필요한 높이 계산
- `Math.ceil(Math.log2(length + 1))`
- `targetLength = targetLength * 2` 
2. **재귀적 검증**
- 트리의 중간 노드(루트)를 기준으로 검증 시작
- 더미 노드(0)는 자식으로 실제 노드(1)를 가질 수 없음
- 서브트리 단위로 재귀적으로 검사
포화 이진트리의 높이(h)와 노드 …
> [태연] 250325

- Programmers/250403_표_편집/choiseona.js
- 문제 이슈 넘버: #166 
- 삭제와 복구가 빈번하게 발생하므로 배열보다 이중 연결 리스트(Doubly Linked List)를 사용합니다.
- 삭제된 행은 스택에 보관하여 가장 최근에 삭제된 행부터 복구할 수 있도록 합니다.
1. **초기화**
- n개의 노드를 가진 이중 연결 리스트를 생성합니다.
- k 위치의 노드를 현재 선택된 노드로 설정합니다.
- 삭제된 노드를 저장할 스택을 준비합니다.
2. **명령어 처리**
- **U X**: X칸 위로 이동 - 현재 노드에서 prev 포인터를 X번 따라갑니다.
- **D X**: X칸 아래로 이동 - 현재 노드에서 next 포인터를 X번 따라갑니다.
- **C**: 현재 행 삭제
- 현재 노드를 삭제 스택에 저장합니다.
- 이전 노드와 다음 노드를 서로 연결합니다.
- 다음 노드가 있으면 다음 노드로 이동, 없으면 이전 노드로 이동합니다.
- **Z**: 최근 삭제된 행 복구
- 스택에서 노드를 꺼냅니다.
- 해당 노드의 이전 노드와 다음 노드에 다시 연결합니다.
- 현재 선택된 노드는 변경하지 않습니다.
3. **결과 생성**
- 길이가 n인 'O'로 채워진 배열을 생성합니다.
- 삭제 스택에 남아있는 노드들의 인덱스 위치에 'X'를 표시합니다.
- 배열을 문자열로 변환하여 반환합니다.
> [선아] 250403

- Programmers/250404_광고_삽입/ssum1ra.py
- 문제 이슈 넘버: #168
- 누적합 활용
- 특정 초에서 재생구간의 수를 구함.
- 해당 배열을 한 번 더 누적합한다.
- 0초부터 x+1초 까지 누적 재생시간을 구하기 위함.
- `t + adv초 까지의 누적 재생시간 - t초 까지의 누적 재생시간`이 가장 큰 t 값을 찾아야 한다.
- 의미 X
> [미라] 250404

- Baekjoon/250407_DNA_비밀번호/rhino-ty.js
- Programmers/250403_표_편집/rhino-ty.js
- 문제 이슈 넘버: #166 
이 문제는 행들로 구성된 표를 편집하는 여러 명령어들을 처리한 후, 최종 상태를 확인하는 문제입니다. 주요 명령어는 다음과 같습니다:
- `U X`: 현재 행에서 X칸 위로 이동
- `D X`: 현재 행에서 X칸 아래로 이동
- `C`: 현재 행 삭제 후 바로 아래 행 선택(마지막 행이면 윗 행)
- `Z`: 가장 최근 삭제된 행 복구(현재 선택된 행은 변경 안됨)
처음에는 행들을 배열로 관리하고, 삭제 시 배열에서 실제로 요소를 제거하는 방식을 고려했습니다. 하지만 이 방법은:
1. 삭제 연산(`C`)마다 O(n) 시간이 소요됨
2. 복구 연산(`Z`)도 O(n) 시간이 필요함
3. n이 최대 1,000,000이므로 시간 초과 가능성이 높음
효율성을 높이기 위해 두 가지 핵심 개념을 적용했습니다.
1. **Soft Delete**
- 행을 실제로 제거하지 않고 삭제 상태만 표시(`table` 배열)
- 이를 통해 원래 행 번호를 항상 추적 가능
2. **연결 리스트**
- 각 행의 이전/다음 행 정보를 별도 배열(`prevRows`, `nextRows`)에 저장
- 삭제/복구 시 포인터만 변경하여 O(1) 시간에 처리
- 이동 명령어도 연결을 따라가므로 효율적
1. **자료구조 설정**
- 행의 상태 저장: `table` 배열 (true: 존재, false: 삭제)
- 연결 정보 저장: `prevRows`, `nextRows` 배열
- 삭제 이력 관리: `deleted` 스택
2. **명령어 처리**
- `U X`: prevRows 배열을 따라가며 X칸 위로 이동
- `D …
> [태연] 250403

- Baekjoon/250407_DNA_비밀번호/choiseona.js
- Baekjoon/250408_문자열_게임_2/choiseona.js
- 문제 이슈 넘버: #173 
30분 
- 슬라이딩 윈도우
> [선아] 250407

- Baekjoon/250408_문자열_게임_2/choiseona.js
> [선아] 250408 

- Baekjoon/250408_문자열_게임_2/dbjoung.js
- 문제 이슈 넘버: #177 
- 1시간
1. 문자열의 각 문자를 순회한다.
2. 각 문자의 아스키코드값을 인덱스로 하여 다음과 같은 내용을 저장.
- 해당 문자의 인덱스.
3. 최소 길이 저장할 변수, 최대 길이 저장할 변수 선언
4. 문자 배열을 순회하며 슬라이딩 윈도우
- 100 * 25 * 10000
> [다솔] 250408

- Baekjoon/250410_녹색_옷_입은_애가_젤다지/choiseona.js
- 문제 이슈 넘버: #182 
- 1시간인데 우선순위큐 이전꺼 가져다 써서 의미가 없는 것 같기도...
- 각 테스트케이스에 대해 시작점 `(0, 0)`에서 도착점 `(N-1, N-1)`까지 이동하면서 잃는 금액의 합이 최소가 되도록 경로를 탐색
- 각 칸의 값을 잃는 금액으로 보고, 가중치가 있는 그래프 문제로 다익스트라 사용
> [선아] 250410

- Baekjoon/250414_인구_이동/choiseona.js
- 문제 이슈 넘버: #187 
- 8:50 시작
- 9:42 종료
- 52분 소요 
- BFS를 이용하여 하나의 연합을 탐색
- 인접한 나라와의 인구 차이가 L 이상 R 이하인 경우, 해당 나라를 같은 연합으로 묶기 
- 연합이 구성되면 해당 연합의 인구를 평균값으로 재분배
- 하루 동안 모든 칸들을 돌았을 때, 새로운 연합이 하나도 생기지 않으면(인구 이동 발생하지 않으면) 종료
> [선아] 250414

- Baekjoon/250414_인구_이동/ssum1ra.py
- 문제 이슈 넘버: #187 
- bfs 활용
- 새로운 연합 찾기
- 20분 안 걸린듯
> [미라] 250414

- Baekjoon/250410_녹색_옷_입은_애가_젤다지/dbjoung.js
> [다솔] 250410

- Baekjoon/250410_녹색_옷_입은_애가_젤다지/dbjoung.js
- Baekjoon/250411_감시/dbjoung.js
- 문제 이슈 넘버: #185 
풀이시간 : 1시간 48분
> [다솔] 250411

- Baekjoon/250415_부분합/dbjoung.js
- 문제 이슈 넘버: #190 
- 풀이 시간 : 41분 (+테케 질문게시판 열람)
- 풀이 방법 : 슬라이딩윈도우 + 이분탐색
> [다솔] 250415

- Baekjoon/250415_부분합/choiseona.js
- 문제 이슈 넘버: #190 
- 9:35 시작, 9:56 끝
- 21분
- 투포인터, 슬라이딩 윈도우
> [선아] 250415

- Baekjoon/250416_하늘에서_별똥별이_빗발친다/ssum1ra.cpp
- 문제 이슈 넘버: #197 
- 빗변에 두 개 이상의 유성이 있다면, 가장 많이 포함될 가능성이 크다.
- 의미 없음
> [미라] 250416

- Programmers/ssum1ra.cpp
- 문제 이슈 넘버: #200 
- 플로이드-마샬 활용
```
for (int k = 0; k < V; ++k) {
for (int i = 0; i < V; ++i) {
for (int j = 0; j < V; ++j) {
dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]);
}
}
}
```
- 40 - 50분 정도
> [미라] 250417

- Programmers/250418_보석_쇼핑/choiseona.js
- 문제 이슈 넘버: #205 
- 1시간
- set , map, 투포인터 활용
1. 전체 보석 종류 수를 `Set`을 통해 구함 
2. `left`, `right` 두 포인터를 사용하여 구간을 확장 또는 축소 
3. 현재 구간에 포함된 보석들을 `Map`에 기록하며, 모든 종류가 들어있는지 확인 
4. 모든 종류가 포함된 경우, 가능한 최소 길이 구간인지 확인하고 정답을 갱신
5. 구간을 0-based index로 추적한 뒤, 최종적으로 `1-based index`로 변환하여 반환
> [선아] 240418

- Programmers/250418_보석_쇼핑/ssum1ra.cpp
- 문제 이슈 넘버: #205 
- 투포인터 활용
- 특정 인덱스의 보석을 반드시 포함하며 모든 보석을 얻을 수 있는 가장 짧은 구간을 찾는다.
- 1시간 정도
> [미라] 250418

- Baekjoon/250421_비슷한_단어/ssum1ra.cpp
- Baekjoon/250421_비슷한_단어/ssum1ra.py
- 문제 이슈 넘버: #210
- 완탐으로 통과
- 이중 for문으로 두 문자열 비교
- 접두사 구하기  
- c++이라 가능
> - 파이썬 풀이
>   - words 정렬
>     - 인접한 단어만 비교하면서 최대 접두사 길이를 구한다.
>   - dictionary에 ```{최대 길이 접두사} : [해당 접두사를 가진 단어들]```를 기록한다.
>   - 해당 접두사 그룹이 2개 이상일 경우, 조합으로 후보 쌍 생성
>   - 조건에 맞는 최종 후보 선택
- c++ 풀이 : 30분 정도
- 파이썬 풀이 : 40분 정도
> [미라] 250421

- Baekjoon/250421_비슷한_단어/choiseona.js
- 문제 이슈 넘버: #210 
- map, set 활용 
1. 단어들을 정렬
2. 인접한 단어와의 접두사 구하기
3. prefixMap에 key:접두사, value:원본 인덱스들 저장 
4. 가장 긴 접두사를 갖는 쌍 중, 가장 작은 인덱스를 가진 2개 선택
> [선아] 250421

- Baekjoon/250422_문자열_폭발/choiseona.js
- 문제 이슈 넘버: #212 
- 6:45 시작
- 7:20 끝
- 35분 
- while로 문자열에서 반복적으로 폭탄 문자열을 찾고, 찾으면 제거하는 방식
- 이중 반복문이고, 불변성 지키는 `includes`와 `replace` 메서드를 사용하기 때문에 시간/메모리 많이듬
- `stack`을 사용해 문자열을 한 글자씩 쌓으며, 폭탄 문자열이 완성되었을 때 제거하는 방식
- 각 문자를 `stack`에 쌓고, `stack`의 마지막 부분에서 폭탄 문자열이 완성되면 이를 `splice`로 제거 
- 문자열을 배열로 처리하고, `slice`와 `splice`를 사용하여 폭탄 문자열을 찾아 제거하는 방식으로, 1번 방식보다 효율적
- 포인터가 폭탄 문자열의 길이를 넘었을 때 뒤에 폭탄 문자열이 있으면 제거하는 방식 
- 문자열을 배열로 변환한 후, 각 문자를 배열에 추가하면서 폭탄 문자열을 찾고, 일치하면 포인터를 조정하여 해당 부분을 제거
- `splice`를 사용하지 않고 포인터만으로 배열을 수정하기 때문에, 메모리 사용이 적고 효율적으로 동작. 2번이랑 시간복잡도랑 공간복잡도가 거의 비슷하지만, 좀 더 효율적
> [선아] 250422

- Baekjoon/250422_문자열_폭발/ssum1ra.cpp
- 문제 이슈 넘버: #212 
- stack 활용
- 한글자씩 입력 받으면서 폭발 문자열을 만나면 없앰.
- 20 - 30분 사이
> [미라] 250422

- Baekjoon/250423_가희의_탑/ssum1ra.cpp
- 문제 이슈 넘버: #218
- 7 3 4의 경우
- 필요한 탑의 최소 개수 찾기
- 가희가 볼 수 있는 탑 : 1, 2, 4
- 단비가 볼 수 있는 탑 : 4, 3, 2, 1
- 총 탑의 수 -> 6개, 추가적으로 탑을 배치해야 한다.
- 사전순으로 가장 앞선 것이 정답이므로, 부족한 만큼 좌측에 높이가 1인 탑 삽입 : (1), 1, 2, 4
- 가희가 볼 수 있는 탑이 한 개인 경우, 부족한 만큼 최고 높이 탑 우측에 높이가 1인 탑 삽입 : 10, (1, 1, ...), 9, 8, 7, ... 
- 40 - 50분 걸린듯
> [미라] 250423

- Programmers/250425_자물쇠와_열쇠
- 문제 이슈 넘버: #223 
- 빨간색을 열쇠, 검은색을 자물쇠라 했을 때
- 모든 열쇠를 대입해 완전 탐색을 한다.
- 이동 범위를 고려한 배열 (2 * M + N) X (2 * M + N)을 만든다.
- 모든 열쇠 방향에 대해 한 칸씩 이동시키며 가능한지 확인한다.
- 의미 없음
> [미라] 250425

- Programmers/250425_자물쇠와_열쇠/choiseona.js
- 문제 이슈 넘버: #223 
- 열쇠는 90도씩 회전시킬 수 있습니다. 이를 위해 `getRotated` 함수를 사용하여 열쇠 배열을 시계방향으로 90도 회전시킵니다.
- 회전된 배열을 구할 때, 배열의 행과 열을 반전시키고, 새로운 배열에 적절하게 값을 할당하여 회전된 결과를 반환합니다.
- `checkCanUnlock` 함수는 주어진 시작 좌표 `(startX, startY)`에서 열쇠가 자물쇠에 맞는지 확인합니다.
- 자물쇠의 크기 `N`과 열쇠의 크기 `M`을 고려하여, 자물쇠 배열을 복사한 후 열쇠의 각 위치에 맞춰 더합니다.
- 열쇠를 겹친 후, 자물쇠 배열의 모든 값이 `1`로 채워졌다면 열쇠가 자물쇠를 완전히 열 수 있다는 뜻이므로 `true`를 반환합니다. 그렇지 않으면 `false`를 반환합니다.
- 열쇠를 90도씩 4번 회전시키며 자물쇠에 맞는지 확인합니다.
- 각 회전마다, 열쇠를 자물쇠 위에서 가능한 모든 위치 `(startX, startY)`에 대해 맞는지 확인합니다.
- 이때, 열쇠가 자물쇠의 범위를 벗어나지 않도록 주의합니다.
- 열쇠가 자물쇠를 열 수 있는 경우 `true`를 반환하고, 그렇지 않으면 `false`를 반환합니다.
> [선아] 250425

- Baekjoon/250428_거짓말/ssum1ra.py
- 문제 이슈 넘버: #227 
- 진실을 아는 사람 목록 만들기
- 간접적으로 아는 사람까지 고려하기 위해 파티 수만큼 반복
- 20분
> [미라] 250428

- Baekjoon/250428_거짓말/choiseona.js
- 문제 이슈 넘버: #227 
- 9:7 시작
- 9:50 끝
- 43분
1. **초기화**
- 진실을 아는 사람들을 `isKnow` 배열에 표시.
2. **진실 퍼뜨리기**
- 모든 파티를 순회하면서, 만약 파티에 진실을 아는 사람이 있으면,
- 그 파티의 모든 참석자에게 진실을 전파.(isKnow 배열 갱신) 
- 새로운 사람이 진실을 알게 될 때마다 `changed`를 `true`로 설정.
- 모든 파티 돈 후에 changed가 true이면 파티 다시 돌면서 반복 
- 더 이상 퍼질 진실이 없을 때까지 이 과정을 반복.
3. **결과 계산**
- 다시 모든 파티를 확인하면서,
- **참석자 중 진실을 아는 사람이 없는 파티**만 카운트하여 결과로 출력.
> [선아] 250428 

- Baekjoon/250409_뱀과_사다리_게임/dbjoung.js
- 문제 이슈 넘버: #179 
bfs 최단경로로 푼다.
단, 뱀이나 사다리를 마주칠 경우 바로 이어진 칸으로 이동해준다.
풀이 시간 : 의미 없음 (다른 풀이 봄 ㅠ)
> [다솔] 250409

- Baekjoon/250423_가희의_탑/dbjoung.cpp
- 문제 이슈 넘버: #218 
- 1시간
- 가희는 건물들의 왼쪽, 단비는 건물들의 오른쪽.
- 일직선 상에 가희, 단비, 건물들 배치.
- 가희, N개의 건물, 단비
- 건물의 개수, 가희가 볼 수 있는 건물 수, 단비가 볼 수 있는 건물 수 입력
- 조건에 맞는 건물들의 높이 정보를 사전순으로 앞선 것 출력. 존재하지 않으면 -1 출력
- 주어진 조건에 맞는 건물 순서 중에서 사전순 정렬 시의 첫번째 케이스를 구하는 것이기 때문에 최대한 낮은 숫자를 배치하도록 해야 하며, 앞쪽에 배치될 수록 좋다.
- 또한, 가희와 단비는 하나의 건물을 중복으로 마주보고 서게 된다.
- 따라서 N 보다 a+b-1 값이 더 크면 건물 배치가 불가능한 케이스다.
- 가희와 단비가 중복으로 보는 건물의 인덱스는 `n-(b-1)` 이고, 가희는 `0`부터 `(n-(b-1))-a+1` 인덱스까지는 1로 채워도 된다.
- `(n-(b-1))-a+1` 부터 중복 건물 인덱스 사이의 인덱스는 `이전 건물 높이 + 1`만큼 채운다.
- 다희 쪽은 역으로 접근하며 1부터 b까지 채우고, 나머지는 전부 1로 배정한다.
- N
> [다솔] 250423

- Baekjoon/250423_가희의_탑/dbjoung.cpp
- Programmers/250425_자물쇠와_열쇠/dbjoung.cpp
- 문제 이슈 넘버: #223 
- 1시간 30분
- 잠겨있는 자물쇠 - 한 칸의 크기가 1x1인 nxn 크기의 정사각 격자 형태.
- 열쇠 - MXM 크기인 정사각 격자 형태
- 열쇠는 회전과 이동이 가능. 자물쇠 영역 내에서 열쇠의 돌기 부분과 자물쇠의 홈이 정확하게 일치해야함.
- M, N 둘 다 최대 20, M<=N
- 0은 홈, 1은 돌기
- 완전 탐색.
- 키 배열을 90도 회전 시키며, 각 방향마다의 매칭 여부를 전부 확인한다.
- [1-keySize, 1-keySize] 칸부터 시작해 [lockSize, lockSize] 칸까지를 첫번째 타일삼아 매칭 검사를 한다.
- 매칭검사에서는 시작칸부터 키와 겹치는 영역 까지를 검사한다.
- vector 자료형의 size()를 음수와 비교할 때 주의가 필요함
- vector 자료형 key의 길이가 3일경우 아래 결과는 1이다. (key.size()의 자료형은 unsigned int이기 때문에, 그와 비교하는 int는 묵시적 형변환이 일어난다.
```printf("%d", -5 > key.size())```
- 계산x
> [다솔] 250425

- Baekjoon/250429_팰린드롬?/ssum1ra.py
- 문제 이슈 넘버: #231
- 매번 팰린드롬 검사
- 시간 초과
- dp 활용
- 수열에서 leftmost와 rightmost의 값이 같고, dp[leftmost + 1][rightmost - 1]가 팰린드롬인 경우
- dp[leftmost][rightmost]는 팰린드롬  
- 40분 쯤??
> [미라] 250429

- Baekjoon/250430_강의실_배정/ssum1ra.py
- 문제 이슈 넘버: #237 
- 시작시간으로 정렬
- 우선순위큐로 종료 시간 관리
- 현재 수업의 시작 시간이 어떤 종료 시간 이후라면, 해당 종료 시간을 제거하고 현재 수업의 종료 시간을 추가한다.
- 종료 시간이 겹쳐서 재사용할 수 없다면, 단순히 현재 수업의 종료 시간을 추가한다.
- 20분 정도?
> [미라] 250430

- Programmers/250501_징검다리_건너기/ssum1ra.py
- 문제 이슈 넘버: #240
- 이분 탐색 활용
- 이분 탐색으로 건널 수 있는 최대 인원 수 m을 찾음.
- m명이 건널 때, 연속 k개 이상의 디딤돌이 m 이하이면 실패.
- 실패하면 더 적은 인원으로 줄여야 하므로 r = m - 1, 성공하면 더 많은 인원도 가능할 수 있으므로 l = m + 1
- 슬라이딩 윈도우 + 우선순위 큐 활용
- k 크기의 윈도우에서 최댓값 중 가장 작은 것이 정답이 된다.
```py
import heapq
def solution(stones, k):
answer = float('inf')
heap = []
for i in range(k-1):
heapq.heappush(heap, (-stones[i], i))
for i in range(k-1, len(stones)):
heapq.heappush(heap, (-stones[i], i))
while heap[0][1] < i - k + 1:
heapq.heappop(heap)
answer = min(answer, -heap[0][0])
return answer
```
- 의미 없음
> [미라] 250501

- Baekjoon/250428_거짓말/choiseona.js
- Programmers/250501_징검다리_건너기/dbjoung.cpp
- 문제 이슈 넘버: #240 
- 풀이 시간 : 40분
- 이분탐색.
- 시간복잡도 : 200000*(20~30)
> [다솔] 250501

- Baekjoon/250429_팰린드롬/dbjoung.js
- Baekjoon/250429_펠린드롬/dbjoung.js
- 문제 이슈 넘버: #231 
- 1시간 7분
- 질문 수가 너무 많으므로 제공된 수열의 모든 펠린드롬을 구한 후, 질문의 인덱스와 대조만 한다.
- 2000*2000
> [다솔] 250429

- Baekjoon/250508_미세먼지_안녕/choiseona.js
- 문제 이슈 넘버: #245 
- 시작 8:15
- 끝: 9:30
- 총 1시간 15분
- 단순 구현 
- 인접한 4방향으로 `Math.floor(양 / 5)` 만큼 확산
- 확산은 동시에 일어나므로 별도의 배열 `spreaded`에 누적한 뒤, 마지막에 원본 map에 반영
- **청정기 위쪽**: 반시계 방향 회전
- **청정기 아래쪽**: 시계 방향 회전
- 순환 과정은 각 방향에 따라 값을 한 칸씩 미는 방식으로 구현
- 청정기에서 나오는 바람 방향의 시작 칸은 항상 `0`으로 세팅
> [선아] 250508

- Baekjoon/250509_게리맨더링/choiseona.js
- 문제 이슈 넘버: #248 
- 시작: 8:20
- 끝: 9:20
- 1시간 정도 걸림 
- 순열, BFS 활용한 구현 
- 도시를 두 그룹으로 나누기 위해, 1개부터 N/2개까지의 모든 조합을 생성
- 한 선거구에 포함되는 도시들을 선택하면, 나머지 도시들은 자동으로 다른 선거구가 됨
- 각 선거구 내의 도시들이 모두 연결되어 있는지 BFS로 확인
- 방문한 노드 수와 그룹 크기 같으면 연결된 것으로 판단 
- 두 선거구의 인구 합을 계산하고 차이값 구하기 
- 가능한 모든 조합에 대해 연결성을 확인하고, 연결된 경우에만 인구 차이를 계산하여 최소 차이 찾기 
- 가능한 조합이 없다면 -1을 반환
> [선아] 250509

- Baekjoon/250514_저울/rhino-ty.js
- 문제 이슈 넘버: #254 
이 문제는 물건들 간의 무게 비교 관계를 방향 그래프로 모델링해 해결했습니다. 핵심 아이디어는 **직접적인 비교 정보**를 바탕으로 **간접적인 비교 가능성**까지 파악하는 것입니다.
무게 비교 관계를 두 가지 방향 그래프로 표현했습니다. 왜냐하면, 비교 가능하다라는 말은 A와 B보다 가볍거나, 무겁거나를 생각해야하기 때문에 그렇게 접근하게 됐습니다.
- **정방향 그래프**: 무거운 물건 → 가벼운 물건
- **역방향 그래프**: 가벼운 물건 → 무거운 물건
이렇게 양방향으로 그래프를 구성함으로써 어떤 물건보다 무거운 물건과 가벼운 물건을 모두 추적할 수 있습니다.
```javascript
// 그래프 초기화 및 구성 부분
const graph = Array.from({ length: N + 1 }, () => []);
const reverseGraph = Array.from({ length: N + 1 }, () => []);
for (let i = 0; i < things.length; i++) {
const [heavy, light] = things[i];
graph[heavy].push(light);
reverseGraph[light].push(heavy);
}
```
각 물건에 대해서 가볍고, 무거운 관계를 파악하기 위해서 위에서 구현했던 2개의 그래프를 사용해 탐색합니다.
1. 정방향 그래프에서 DFS를 수행해 **해당 물건보다 가벼운 모든 물건** 탐색
2. 역방향 그래프에서 DFS를 수행해 **해당 물건보다 무거운 모든 물건** 탐색
```javascript …
```
> [태연] 250514

- Programmers/250417_합승_택시_요금/rhino-ty.js
- 문제 이슈 넘버: #200
두 사람(A, B)이 같은 출발지(S)에서 각자의 목적지(A와 B)로 택시를 타고 이동할 때, 일부 구간을 합승해 총 택시 요금을 최소화하는 문제입니다. 
다익스트라 알고리즘을 3번 실행해 필요한 모든 최단 거리를 미리 계산한 후, 가능한 모든 합승 종료 지점을 확인합니다.
1. **그래프 초기화**
- 노드 수(n)에 맞는 인접 리스트 그래프 생성 (1부터 n까지)
- 주어진 간선 정보(fares)로 양방향 그래프 구성
- 각 노드마다 연결된 노드와 비용 저장 [연결노드, 비용]
2. **다익스트라 알고리즘 함수 구현**
- 시작 노드에서 다른 모든 노드까지의 최단 거리 계산
- 최소힙 사용하여 가장 가까운 노드부터 처리
- 방문하지 않은 노드 중 최단 거리가 가장 짧은 노드 선택
- 해당 노드를 거쳐 다른 노드로 가는 비용 계산 및 최단 거리 갱신
3. **모든 가능한 합승 지점 탐색**
- 출발점(s)에서 시작하는 다익스트라 알고리즘 실행 → 모든 노드까지의 최단 거리 저장
- A의 도착점(a)에서 시작하는 다익스트라 알고리즘 실행 → 모든 노드까지의 최단 거리 저장
- B의 도착점(b)에서 시작하는 다익스트라 알고리즘 실행 → 모든 노드까지의 최단 거리 저장
4. **최소 비용 계산**
- 초기 최소 비용 = 무한대로 설정
- 모든 노드(i)에 대해 반복:
- 합승하지 않는 경우: s→a 비용 + s→b 비용
- 합승하는 경우: s→i 비용 + i→a 비용 + i→b 비용
- 두 경우 중 최소값 선택하여 갱신
5. **결과 반환**
- 계산된 최소 비용 반환
- …
> [태연] 250417

- Programmers/250418_보석_쇼핑/rhino-ty.js
- 문제 이슈 넘버: #205 
**모든 종류의 보석을 포함하는 가장 짧은 구간을 찾는** 전형적인 투 포인터 문제라고 생각했습니다. 배열이나 문자열에서 특정 조건을 만족하는 부분 배열을 찾을 때 매우 유용해서 사용했습니다.
1. **투 포인터 알고리즘** 
- 시작 포인터(`start`)와 끝 포인터(`end`)를 이용해 구간 조절
- 조건 충족 여부에 따라 포인터 이동 방식
2. **핵심 데이터 구조**
- `Set`: 총 보석 종류 수를 파악하기 위해 사용
- `Map`: 현재 구간에 포함된 보석 종류와 각 보석의 개수를 추적하기 위해 사용
3. **알고리즘 흐름**
```
- 끝 포인터 증가 → 구간 확장 → 조건 만족 여부 확인
- 조건 만족 시 시작 포인터 증가 → 구간 최소화 → 최적해 갱신
```
Map을 사용하면 보석 종류와 개수를 효율적으로 관리할 수 있고, has나 size 메서드를 활용해 조건 만족 여부를 쉽게 확인할 수 있었습니다.
- end 포인터: 모든 종류의 보석을 포함할 때까지 계속 증가
- start 포인터: 모든 종류를 포함한 상태에서 구간을 최소화하기 위해 증가
`end` 포인터가 배열 끝에 도달하면 알고리즘을 종료합니다.
- 시간 복잡도: **O(2n)** - 각 원소는 최대 2번(`start`와 `end` 포인터로) 방문
- 공간 복잡도: **O(k)** - k는 보석의 종류 수
> [태연] 250418

- Baekjoon/250430_강의실_배정/rhino-ty.js
- 문제 이슈 넘버: #237 
이 문제는 각 수업의 시작 시간(Si)과 종료 시간(Ti)이 주어졌을 때, 모든 수업을 진행하기 위해 필요한 최소 강의실 개수를 구하는 문제입니다. 수업이 끝난 직후에 다른 수업을 시작할 수 있습니다(Ti ≤ Sj인 경우 같은 강의실 사용 가능).
처음에는 시간 범위가 10^9로 매우 커서 일반 배열이나 DP를 사용하기 어렵다는 것을 파악했습니다. 이런 큰 범위에서는 모든 시간을 고려하는 것보다 '강의'가 발생하고 종료되는 시점만 고려하는 것이 효율적이라고 생각했습니다.
1. 모든 수업의 시작과 종료를 개별 이벤트 간주
- 시작 이벤트: 강의실 사용 시작 (+1)
- 종료 이벤트: 강의실 반납 (-1)
2. 이벤트들을 시간 순서대로 정렬
- 시간이 다르면 시간 순으로 정렬
- 시간이 같으면 종료 이벤트가 먼저 오도록 정렬 (강의실 재사용 가능)
3. 정렬된 이벤트를 순차적으로 처리
- 시작 이벤트가 발생하면 강의실 수 증가 (+1)
- 종료 이벤트가 발생하면 강의실 수 감소 (-1)
- 필요한 강의실의 최대 개수를 기록
4. 최종적으로 필요한 최소 강의실 수는 이 최대값이 됨
1. 각 수업마다 시작 이벤트와 종료 이벤트를 분리 후 생성해 배열에 저장
2. 이벤트들을 시간 순으로 정렬했고, 같은 시간에는 종료 이벤트가 먼저 처리되도록 정렬
3. 정렬된 이벤트를 순서대로 처리하면서 현재 필요한 강의실 개수 계산
4. 과정 중 필요한 강의실의 최대 개수를 기록해 반환
- 이벤트 생성: O(N)
- 이벤트 정렬: O(N log N)
- 이벤트 처리: O(N)
- 전체 시간 복잡도: …
> [태연] 250430

- Baekjoon/250429_팰린드롬?/rhino-ty.js
- 문제 이슈 넘버: #231 
이 문제는 수열의 부분 구간이 팰린드롬인지를 효율적으로 판별하는 문제입니다. 
- 수열의 크기 N: 최대 2,000
- 질문의 개수 M: 최대 1,000,000개
- 각 질문은 S부터 E까지의 부분 수열이 팰린드롬인지 물어봄(1-base)
>[!TIP]
>**팰린드롬**: 앞에서부터 읽으나 뒤에서부터 읽으나 같은 순서가 되는 수열
단순히 각 질문마다 팰린드롬 여부를 확인하면, 투포인터 등으로 효율화를 해도 $O(N×M)$ 시간이 소요돼 시간 초과가 발생합니다. 따라서 동적 계획법(DP)을 활용해 모든 부분 수열의 팰린드롬 여부를 미리 계산해두는 방식으로 접근했습니다.
- **DP 정의**: `DP[i][j]` = i번째 수부터 j번째 수까지의 부분 수열이 팰린드롬인지 여부 (1: 팰린드롬, 0: 아님)
- **점화식**
1. 길이가 1인 부분 수열: `DP[i][i] = 1` (항상 팰린드롬)
2. 길이가 2인 부분 수열: `DP[i][i+1] = (arr[i] == arr[i+1] ? 1 : 0)`
3. 길이가 3 이상인 부분 수열: `DP[i][j] = (arr[i] == arr[j] && DP[i+1][j-1])`
1. DP 배열 초기화 (N×N 크기)
2. 길이 1과 2인 부분 수열부터 팰린드롬 여부를 채움
3. 길이 3부터 N까지 모든 가능한 부분 수열에 대해 점화식 적용
- 3부터 N까지 쌓이고, 1과2가 이미 적용됐으니 직전 -1만 계산해주면 됨
- 모든 시작점 i에 대해 끝점 j = i+len-1 계산
- `DP[i][j] = (arr[i]==arr[j] && …
> [태연] 250429

- Baekjoon/250422_문자열_폭발/rhino-ty.js
- 문제 이슈 넘버: #212 
- 문자열에서 특정 패턴('**폭발 문자열**')을 발견할 때마다 **해당 패턴을 제거**
- 이 과정을 더 이상 **폭발 문자열이 존재하지 않을 때까지 반복**
- 문자열은 1,000,000개, 폭발 문자열은 36개
단순 반복 및 `replace`(최악일 시 $O(n^2)$ )으로는 1,000,000 * 36개를 비교할 수 있어 최악입니다. 또한, JS 특성상 문자열에서 폭발이 일어날 때마다 매번 새 문자열을 생성해야 하는 비효율성이 존재해 새 자료구조가 필요했습니다.
문제 해결을 위해 스택(Stack) 자료구조를 활용하는 접근법을 선택했습니다.
1. 문자열을 한 글자씩 순회하며 스택에 추가
2. 스택의 최근 요소들이 폭발 문자열과 일치하는지 확인
3. 일치한다면 해당 요소들을 스택에서 제거 (`pop`)
이렇게 된다면 아래의 효과를 얻을 수 있습니다.
- 매번 새 문자열을 생성할 필요가 없음
- 연쇄 폭발을 자연스럽게 처리할 수 있음
- 한 번의 순회로 모든 폭발을 처리 가능 ($O(n)$ 시간 복잡도)
초기 구현에서는 `stack.slice().join('')`을 사용하여 매번 새 배열과 문자열을 생성했지만, 이를 직접 요소 비교 방식으로 변경해 성능을 개선했습니다.
```javascript
// 최적화 전
const curStr = stack.slice(stack.length - boomLen).join('');
if (curStr === boomStr) { /* ... */ }
// 최적화 후
let isBoom = true;
for (let j = 0; j < …
```
> [태연] 250422

- Baekjoon/250502_성냥개비/ssum1ra.py
- 문제 이슈 넘버: #243
- 가장 큰 수 찾기
- 작은 성냥개비를 활용하는 숫자들을 통해 자릿수를 최대로 만들어야 한다.
- 가장 작은 수 찾기
- dp 활용
- 특정 수의 성냥개비 활용해서 만들 수 있는 가장 작은 수
- dp[i] = min(dp[i], int(str(dp[j]) + str(dp[i-j])))
- 40분 쯤
> [미라] 250502

- Baekjoon/250519_야구/ssum1ra.py
- 문제 이슈 넘버: #257 
- 시뮬레이션
- 문제 이해하는데 시간이 걸림 
- python3 시간 초과
- pypy3 통과 
- 30분
> [미라] 250519

- Baekjoon/250521_단어_섞기/ssum1ra.py
- 문제 이슈 넘버: #263
- dp 활용
- dp[i][j] = True의 의미
- a의 처음 i개 문자 + b의 처음 j개 문자를 사용해서
- c의 처음 i + j개 문자를 순서를 지키며 만들 수 있다.
- 의미 없음
> [미라] 250521

- Baekjoon/250519_야구/choiseona.js
- 문제 이슈 넘버: #257 
1시간 30분 
1. **순열 생성 (Permutation)**
- 1번 선수를 제외한 2\~9번 선수(인덱스 1\~8)를 대상으로 가능한 타순을 모두 구함 (8! = 40320가지).
- 각 순열에 대해 1번 선수를 **4번째(인덱스 3)** 자리에 삽입하여 타순을 완성.
2. **게임 시뮬레이션**
- 각 타순 조합마다 전체 이닝(0~N-1)을 순회하며 경기를 시뮬레이션함.
- 각 이닝은 3아웃이 될 때까지 진행되며, 주자 상태(map 배열)를 유지하면서 점수를 계산.
3. **타자 이동 처리**
- 안타, 2루타 등 타자의 결과에 따라 주자들을 이동시킴.
- 이동한 주자가 홈을 넘어서면 점수에 반영.
4. **점수 누적 및 최대 점수 갱신**
- 각 타순 조합마다 누적된 총 점수를 계산하고, 지금까지의 최대 점수와 비교하여 갱신.
> [선아] 250519 

- Programmers/250516_카드_짝_맞추기/choiseona.js
- 문제 이슈 넘버: #256 
1시간 30분 정도 
- 보드를 순회하여 각 카드 번호(key)마다 위치 좌표 (2개)(value)를 `Map`에 저장함.
- 카드 번호들의 순열을 구하여 가능한 모든 제거 순서를 탐색함.
- 특정 카드 쌍을 선택할 때 두 카드 중 어떤 것을 먼저 선택할지 두 경우를 모두 시뮬레이션.
- 각 경우에 대해 다음과 같은 방식으로 조작 횟수를 구함:
- **일반 방향키**: 한 칸 이동. -> 조작 횟수 1
- **Ctrl + 방향키**: 해당 방향에 있는 가장 가까운 카드 or 끝 지점으로 이동. -> 조작 횟수1
- 카드 선택 시에는 **엔터 입력** -> 조작 횟수1
- 커서 위치에서 목표 카드 위치까지 이동할 때 BFS를 사용하여 최단 거리 탐색.
- 일반 이동과 Ctrl 이동 모두 고려하여 큐에 넣고 탐색.
- 각 카드 제거 순서에 대한 조작 횟수를 비교하여 최소값을 계속 업데이트.
> [선아] 250516

- Baekjoon/250521_단어_섞기/choiseona.js
- 문제 이슈 넘버: #263 
의미 없음 
- `dp[i][j] = true`  
⇒ `word1`의 처음 `i`글자와 `word2`의 처음 `j`글자를 섞어 `result`의 처음 `i + j`글자를 만들 수 있는 경우
- `dp[0][0] = true`  
⇒ 아무 문자도 사용하지 않았을 땐 항상 만들 수 있음
- `dp[i][j]`가 `true`인 경우,
- `word1[i] === result[i + j]`이면 `dp[i + 1][j] = true`
- `word2[j] === result[i + j]`이면 `dp[i][j + 1] = true`
- 만약 `word1.length + word2.length !== result.length` 이면, 조합 자체가 불가능하므로 `false` 리턴
> [선아] 250521

- SWEA/250522_보급로/choiseona.cpp
- 문제 이슈 넘버: #266 
40분 정도? 
- 다익스트라 
1. **초기화**
- 각 칸까지의 최소 비용을 저장할 2차원 배열 `dist`를 생성하고, 모든 값을 무한대로 초기화
- 시작 위치인 (0,0)의 비용은 해당 칸의 비용으로 설정
2. **우선순위 큐 사용**
- 현재까지의 누적 비용과 좌표를 저장하는 우선순위 큐를 이용해, 가장 비용이 적은 경로부터 탐색
3. **탐색 과정**
- 큐에서 비용이 가장 낮은 노드를 꺼내 현재 위치에서 상하좌우 인접한 칸으로 이동 가능한지 검사
- 이동 가능한 칸에 대해, 기존에 기록된 최소 비용보다 현재 경로의 비용이 적으면 비용을 갱신하고 큐에 추가.
- 이 과정을 큐가 빌 때까지 반복
4. **결과 도출**
- 모든 탐색이 끝난 후, 목적지 (N-1,N-1) 칸에 저장된 최소 비용이 정답
> [선아] 250522

- Baekjoon/250523_문제집/ssum1ra.py
- 문제 이슈 넘버: #269
- 진입 차수가 0인 노드를 힙에 넣고 시작
- 힙에서 하나씩 꺼내며 연결된 노드들의 진입 차수를 줄이고, 0이 되면 다시 힙에 넣음
- 30분
> [미라] 250523

- Baekjoon/250526_여행_가자/ssum1ra.py
- 문제 이슈 넘버: #271
- 플로이드-워셜 활용
- 간접적으로 도착할 수 있는 지 확인 
- 35분 정도...?
> [미라] 250526

- Baekjoon/250528_좋다/ssum1ra.java
- 문제 이슈 넘버: #277
- 투포인터 활용
- 배열 정렬
- 각 수를 한 번씩 target으로 고정
- 그 target을 만들 수 있는 다른 두 수를 투 포인터로 탐색
- 합이 target보다 작으면 → left++
- 합이 크면 → right--
- 합이 같으면 → count++, 다음 수로 넘어감
- X
> [미라] 250528

- Baekjoon/250529_치즈/ssum1ra.java
- 문제 이슈 넘버: #279 
- 외부 공기 표시
- 외부 공기와 2면 이상 맞닿아 있다면, 삭제
- 치즈가 다 사라질 때까지 반복
- 30분
> [미라] 250529

- Baekjoon/250530_새로운_게임_2/ssum1ra.js
> [미라] 250530

- Baekjoon/250604_숨바꼭질_4/ssum1ra.py
- Baekjoon/250605_데스노트/ssum1ra.py
- Programmers/250604_의상/ssum1ra.py
- Programmers/250604_전화번호_목록/ssum1ra.py
- Programmers/250605_베스트앨범/ssum1ra.py
- 문제 이슈 넘버: #298
- dp[i]는 i번째 이름부터 끝까지 적을 때의 최소 비용 저장. 즉, i번째 이름이 맨 앞에 오는 경우의 비용
- 각 위치 i에서 줄의 끝 후보 j까지 모든 가능 조합을 탐색하며, 줄이 넘지 않으면 남는 칸 제곱 비용 + dp[j+1]로 갱신
- 해당 줄에
- i번째 한 개만 존재
- i번째, i + 1번째 두 개 존재 
- ...
- X
---
- 문제 이슈 넘버: #300
- 딕셔너리
- 장르별 재생수
- 재생 수에 따라 장르 정렬
- 장르별 (재생수, 노래번호) 배열
- 재생 수와 노래번호에 따라 배열 정렬 
- 20분
> [미라] 250605

- Baekjoon/250604_숨바꼭질_4/ssum1ra.py
- Programmers/250604_의상/ssum1ra.py
- Programmers/250604_전화번호_목록/ssum1ra.py
- 문제 이슈 넘버: #293
- bfs 활용
- 30분
---
- 문제 이슈 넘버: #295
- **풀이 1**
- 사전순 정렬로 접두어는 인접하므로, 이웃끼리 비교해 접두어 여부 판별
- **풀이 2**
- 모든 번호의 모든 접두어를 딕셔너리에서 찾아 존재하는지 검사
- 10분?
---
- 문제 이슈 넘버: #296
- 의상 종류별로 안 입는 경우를 포함해 조합을 곱하고, 전부 안 입는 경우 1가지를 빼준다.
- 10분?
> [미라] 250604

- Baekjoon/250603_우체국/choiseona.js
- 문제 이슈 넘버: #290 
-  9:5 시작
- 9:23 시간초과
- 9:45 정답
- 총 40분 
- 우체국 기준 왼쪽과 오른쪽 인구 수 차이가 가장 적은 곳에 우체국 세우기
> [선아] 250603

- Baekjoon/250609_개미굴/choiseona.js
- 문제 이슈 넘버: #305 
X
- 각 노드는 `children`이라는 Map을 가지는 클래스로 정의.
- key는 먹이 이름, value는 해당 먹이 이후의 경로를 나타내는 하위 Node.
- 중복 경로를 방지하고, 사전 순 정렬을 용이하게 하기 위해 Map 사용.
- 입력 배열의 첫 원소는 먹이 수를 의미하므로 제외하고, 나머지를 경로로 사용.
- 트리의 루트부터 시작해 현재 경로의 각 먹이를 순회하면서 자식 노드를 추가하거나 이동.
- 이미 존재하는 경로는 재사용하고, 없는 경로만 새로 생성.
- 루트 노드에서 시작해 DFS로 자식 노드를 순회.
- 자식 노드는 Map의 key들을 정렬한 뒤 순회하여 사전 순 출력 보장.
- 출력 시 깊이(`depth`)만큼 `"--"`를 반복하여 들여쓰기 형태로 표현.
> [선아] 250609

- Programmers/250605_베스트앨범/choiseona.js
- 문제 이슈 넘버: #
1. **장르별 총 재생 횟수를 계산**  
- 각 장르에 속한 노래들의 재생 횟수를 모두 더함 
2. **각 노래에 대해 장르, 재생 횟수, 고유 번호, 장르별 총 재생 횟수를 묶어서 관리**
3. **노래들을 정렬**  
- 먼저, 장르별 총 재생 횟수가 높은 장르 순으로 정렬  
- 그 다음, 장르 내에서 재생 횟수가 많은 노래 순으로 정렬  
- 재생 횟수가 같다면 고유 번호가 낮은 순으로 정렬
4. **정렬된 리스트에서 각 장르별로 최대 두 곡씩 선택**
> [선아] 250605

- Baekjoon/250610_최소_스패닝_트리/choiseona.js
- Programmers/250610_같은_숫자는_싫어/choiseona.js
- Programmers/250610_기능개발/choiseona.js
- 문제 이슈 넘버: #
X
1. **간선 정렬**
- 모든 간선을 **가중치 기준 오름차순 정렬**.
- 최소 비용 간선부터 선택할 수 있도록 준비.
2. **유니온 파인드(Union-Find) 구조 활용**
- 각 노드는 처음에 자기 자신을 부모로 가짐.
- `find(x)`를 통해 루트 부모를 찾고, 경로 압축 적용.
- `union(a, b)`로 두 정점의 부모를 병합.
- `find(a) === find(b)`인 경우 사이클이 생기므로 해당 간선은 스킵.
3. **Kruskal 알고리즘 적용**
- 정렬된 간선을 순회하며, 사이클이 생기지 않는 간선을 선택.
- 선택된 간선의 가중치를 누적.
- 간선 개수가 `V - 1`개가 되면 MST 구성 완료로 루프 종료.
- 결과를 담을 빈 배열 `answer` 선언.
- 입력 배열을 순회하면서, 현재 값이 `answer`의 마지막 값과 다를 경우에만 추가.
- 즉, **이전 값과 다를 때만 push**하여 연속 중복을 제거.
- 각 작업별로 남은 날짜(`remainDays`)를 계산 (`Math.ceil((100 - progress) / speed)`).
- `maxRemainDay`는 현재 배포 그룹의 기준일.
- 순회하며 현재 작업의 남은 일수가 기준일보다 크면 **새로운 배포 그룹 시작**.
- 기준일보다 작거나 같으면 **현재 배포 그룹에 포함**.
- `answer` 배열에 각 배포 그룹마다 배포되는 기능 수를 누적.
> [선아] 250610

- Baekjoon/250612_다리_만들기/choiseona.js
- Baekjoon/250613_행렬_곱셈_순서/choiseona.js
- 문제 이슈 넘버: #320 
X
1. **DP 테이블 정의**  
dp[i][j]를 i번째 행렬부터 j번째 행렬까지 곱하는 데 필요한 최소 곱셈 횟수라고 정의
2. **초기값 설정**  
i번째 행렬만 있을 경우 곱셈이 필요 없으므로 dp[i][i] = 0으로 초기화
3. **점화식**  
i부터 j까지 곱하는 최소 비용은,  
i ≤ k < j인 k에 대해,  
dp[i][j] = min(dp[i][j], dp[i][k] + dp[k+1][j] + cost(i~k, k+1~j))  
여기서 cost(i~k, k+1~j)는 i~k까지 곱한 행렬과 k+1~j까지 곱한 행렬을 곱할 때 필요한 곱셈 연산 수
4. **곱셈 연산 비용 계산 방법**  
matrix[i-1][0] * matrix[k-1][1] * matrix[j-1][1]
5. **구현 순서**  
- 길이(length)를 2부터 N까지 늘려가며  
- i부터 j = i + length - 1까지의 부분 문제를 푼다  
- k를 i부터 j-1까지 움직이며 최소 비용을 갱신
6. **최종 답**  
dp[1][N]에 전체 행렬을 곱하는데 필요한 최소 곱셈 연산 횟수가 저장
> [선아] 250613

- Baekjoon/250612_다리_만들기/ssum1ra.py
- 문제 이슈 넘버: #315
- 하나의 섬 내부 BFS로 labeling
- 다리 놓기 BFS
- 방문하지 않은 0을 만나면 → 거리 1씩 증가하면서 확장
- 만약 다른 섬(을 만나면 → 거리 합으로 다리 길이 계산
- 1시간
> [미라] 250612

- Baekjoon/250530_새로운_게임_2/rhino-ty.js
- 문제 이슈 넘버: #282 
체스판 위에서 말들이 특정 규칙에 따라 이동하며, 4개 이상 쌓이는 턴을 찾는 시뮬레이션 문제입니다.
- **시뮬레이션**: 문제에서 주어진 규칙을 그대로 구현 => 의사코드 매우 중요!@
- **스택 구조**: 각 칸에 쌓인 말들을 배열로 관리하여 자연스러운 쌓임 표현
- **효율적인 그룹 이동**: `splice()`를 활용해 말과 그 위의 모든 말을 한 번에 처리
```javascript
const board = [];           // 체스판 색깔 정보
const stackedHorses = [];   // 각 칸에 쌓인 말들 (스택)
const horseMap = {};        // 각 말의 [row, col, direction] 정보
```
1. **입력 파싱**: 체스판과 말 정보 초기화
2. **시뮬레이션**: 1-1000턴, 각 턴마다 1-K번 말 순서대로 이동
3. **이동 처리**:
- 다음 위치 계산 및 유효성 검사
- 파란색/범위밖 시 방향 반대로 변경
- `splice()`로 이동할 말들 추출
- 목적지 색깔에 따른 쌓기 처리
4. **종료 조건**: 4개 이상 쌓이면 턴 반환
다른 코드를 참고해서 수정이 들어간 부분도 포함했습니다.
```javascript
// splice()로 현재 말부터 위의 모든 말을 한 번에 추출+제거
let movingHorses = stackedHorses[r][c].splice(stackedHorses[r][c].indexOf(horseNum));
```
제거+추출을 동시에 하는 `splice()`를 써서 …
> [태연] 250530

- Baekjoon/250606_정육점/rhino-ty.js
- Programmers/250605_베스트앨범/rhino-ty.js
- 문제 이슈 넘버: #302 
어떠한 고깃덩이를 사고, 그보다 싼 고깃덩이는 전부 무료입니다. 여기서, 살 수 있는 최소 가격을 구하는 문제입니다. 저는 정렬 후 그리디하게 접근해봤습니다.
1. 가격 기준으로 내림차순 정렬
2. 전체 무게 합 구함
3. 가장 비싼 것부터 하나씩 제거하면서, 남은 무게가 여전히 M 이상인지 확인
4. M 미만이 되는 순간, 바로 직전에 제거하려던 고기의 가격이 답
20분? 정도 걸렸습니다. 너무 쉬웠던,,
---
- 문제 이슈 넘버: #300 
베스트앨범 정렬하는 문제였습니다. 각 장르마다 플레이 수 계산, 정렬 => 각 장르마다의 노래 플레이 수 정렬 => 2개씩 끊어 반환
> [태연] 250606

- Baekjoon/250618_대표_선수/ssum1ra.py
- 문제 이슈 넘버: #330
- 완전탐색 시간 초과
- 투포인터 + 최소 힙
- 각 반 정렬
- 각 반에서 가장 작은 값 하나씩 가져와 힙에 넣음
- 최소 힙 돌면서, 범위 줄이기
- 꺼낸 반에서 다음 사람 넣기
- 한 반에서 더 이상 선택할 사람이 없으면 → 조합 끝
- X
> [미라] 250618

- Baekjoon/250619_List_of_Unique_Numbers/ssum1ra.py
- 문제 이슈 넘버: #333 
- 투 포인터를 통해 중복이 없는 구간 [start ~ end] 유지
- end를 하나씩 오른쪽으로 늘림
- 중복이 생기면 start를 이동시켜서 중복 제거
- end를 끝으로 하는 중복 없는 모든 구간의 개수는 → end - start + 1 (시작 지점의 개수) 
- 1시간...
> [미라] 250619

- Baekjoon/250622_공주님의_정원/ssum1ra.py
- 문제 이슈 넘버: #337 
- 그리디
- 특정 시점에 피어있는 꽃들 중에서 가장 늦게 지는 꽃을 선택
- 45분 정도
> [미라] 250620

- Baekjoon/250625_동전_1/ssum1ra.py
- 문제 이슈 넘버: #347 
- `dp[i]`: i원을 만드는 방법의 수를 저장
- **동전 하나씩 차례로 고려**하면서 누적
- `dp[i] += dp[i - coin]`: 기존에 i - coin원을 만들 수 있는 방법들에 coin 하나를 추가하여 i원을 만드는 모든 방법을 누적
- 35분 정도
> [미라] 250625
